import type { Bounty } from "@/lib/bounties"
import type { Locale } from "@/lib/i18n"

export const bountyCopy = {
  en: {
    eyebrow: "A little challenge. A good reason to build.",
    description: "Make something, share it with the community, and put your work in the running. Small quests with something good on the other side.",
    explore: "Explore the board", how: "How it works", board: "The bounty board",
    boardTitle: "An idea. A deadline. Your move.",
    open: "Open", closed: "Closed", archive: "Archive", brief: "Read the brief",
    quiet: "No open bounties right now.", quietBody: "Explore the last challenge. Join the community for what comes next.",
    latest: "From the archive", live: "Up for grabs", reward: "The reward", tickets: "conference tickets",
    deadline: "Submission deadline", event: "The event", location: "In person · UTEC Barranco, Lima",
    challenge: "The challenge", challengeIntro: "A few steps from an idea to a finished entry.",
    rewards: "Five tickets. Two ways in.", speakers: "People you'll learn from", speakersIntro: "On the AI Frontier Conf '26 lineup.",
    eventLink: "Explore the conference", all: "All bounties", join: "Join the Discord",
    questions: "Need a hand?", questionsBody: "Ask in the bounty forum. The community is a good place to start.",
    forum: "Ask a question", closedTitle: "That's a wrap for this one.",
    closedBody: "Submissions are closed. Thanks to everyone who built something and shared it.",
    entry: "Your entry", signInBody: "Sign in with your Crafter account to send your post.",
    signIn: "Sign in to participate", closingNote: "All deadlines are shown in Lima time (UTC−5).",
    howTitle: "From “what if” to “look at this”.",
    process: [
      { title: "Pick a challenge.", body: "Read the brief, the reward, and the deadline. Every bounty has its own rules." },
      { title: "Make it yours.", body: "Build something worth sharing. Show your process and what you made." },
      { title: "Put it out there.", body: "Share your work and send your entry before the deadline. The brief explains how rewards are awarded." },
    ],
    invitation: "Better with a little company.",
    invitationBody: "Trade ideas, find a second pair of eyes, and meet the people building alongside you.",
    attendance: "You must be able to attend in person. Winner announcement was scheduled for October 5.",
  },
  es: {
    eyebrow: "Un pequeño reto. Una buena excusa para crear.",
    description: "Construye algo, compártelo con la comunidad y pon tu trabajo en juego. Pequeños retos con algo bueno al otro lado.",
    explore: "Explorar los retos", how: "Cómo funciona", board: "El tablero de bounties",
    boardTitle: "Una idea. Una fecha. Tu turno.",
    open: "Abierto", closed: "Cerrado", archive: "Archivo", brief: "Ver el reto",
    quiet: "Por ahora no hay bounties abiertos.", quietBody: "Explora el último reto. Súmate a la comunidad para lo que viene.",
    latest: "Del archivo", live: "En juego", reward: "La recompensa", tickets: "entradas a la conferencia",
    deadline: "Cierre de envíos", event: "El evento", location: "Presencial · UTEC Barranco, Lima",
    challenge: "El reto", challengeIntro: "Unos pasos de la idea a tu participación.",
    rewards: "Cinco entradas. Dos caminos.", speakers: "Gente de quien aprender", speakersIntro: "En el programa de AI Frontier Conf '26.",
    eventLink: "Conocer la conferencia", all: "Todos los bounties", join: "Únete al Discord",
    questions: "¿Una mano?", questionsBody: "Deja tu pregunta en el foro del bounty. La comunidad es un buen lugar para empezar.",
    forum: "Hacer una pregunta", closedTitle: "Este reto ya cerró.",
    closedBody: "Ya no recibimos envíos. Gracias a quienes construyeron algo y lo compartieron.",
    entry: "Tu participación", signInBody: "Inicia sesión con tu cuenta de Crafter para mandar tu post.",
    signIn: "Iniciar sesión para participar", closingNote: "Los horarios de cierre están en hora de Lima (UTC−5).",
    howTitle: "Del «¿y si…?» al «mira esto».",
    process: [
      { title: "Encuentra tu reto.", body: "Revisa la propuesta, el premio y la fecha. Cada bounty tiene sus propias reglas." },
      { title: "Hazlo tuyo.", body: "Construye algo que quieras compartir. Muestra tu proceso y lo que hiciste." },
      { title: "Sácalo al mundo.", body: "Comparte tu trabajo y envíalo antes del cierre. El reto explica cómo se reparten los premios." },
    ],
    invitation: "Mejor con un poco de compañía.",
    invitationBody: "Cruza ideas, encuentra un segundo par de ojos y conoce a quienes están construyendo contigo.",
    attendance: "Debes poder asistir presencialmente. El anuncio de ganadores estaba previsto para el 5 de octubre.",
  },
  pt: {
    eyebrow: "Um pequeno desafio. Um bom motivo para criar.",
    description: "Crie algo, compartilhe com a comunidade e coloque seu trabalho em jogo. Pequenos desafios com algo bom do outro lado.",
    explore: "Explorar os desafios", how: "Como funciona", board: "O mural de bounties",
    boardTitle: "Uma ideia. Um prazo. Sua vez.",
    open: "Aberto", closed: "Encerrado", archive: "Arquivo", brief: "Ver o desafio",
    quiet: "Nenhum bounty aberto por enquanto.", quietBody: "Explore o último desafio. Entre na comunidade para acompanhar os próximos.",
    latest: "Do arquivo", live: "Em jogo", reward: "A recompensa", tickets: "ingressos para a conferência",
    deadline: "Prazo de envio", event: "O evento", location: "Presencial · UTEC Barranco, Lima",
    challenge: "O desafio", challengeIntro: "Alguns passos da ideia à sua participação.",
    rewards: "Cinco ingressos. Dois caminhos.", speakers: "Gente com quem aprender", speakersIntro: "Na programação da AI Frontier Conf '26.",
    eventLink: "Conhecer a conferência", all: "Todos os bounties", join: "Entre no Discord",
    questions: "Precisa de uma mão?", questionsBody: "Deixe sua pergunta no fórum do bounty. A comunidade é um bom lugar para começar.",
    forum: "Fazer uma pergunta", closedTitle: "Este desafio chegou ao fim.",
    closedBody: "Os envios estão encerrados. Obrigado a quem criou algo e compartilhou.",
    entry: "Sua participação", signInBody: "Entre com sua conta Crafter para enviar seu post.",
    signIn: "Entrar para participar", closingNote: "Os prazos seguem o horário de Lima (UTC−5).",
    howTitle: "Do “e se…” ao “olha isso”.",
    process: [
      { title: "Encontre seu desafio.", body: "Confira a proposta, o prêmio e o prazo. Cada bounty tem suas próprias regras." },
      { title: "Faça do seu jeito.", body: "Crie algo que queira compartilhar. Mostre seu processo e o resultado." },
      { title: "Mostre ao mundo.", body: "Compartilhe seu trabalho e envie antes do prazo. O desafio explica como os prêmios são distribuídos." },
    ],
    invitation: "Melhor com um pouco de companhia.",
    invitationBody: "Troque ideias, encontre um segundo olhar e conheça quem está criando com você.",
    attendance: "É preciso poder participar presencialmente. O anúncio dos ganhadores estava previsto para 5 de outubro.",
  },
  zh: {
    eyebrow: "一个小挑战。一个动手创造的好理由。",
    description: "创造作品，与社区分享，让你的成果参与角逐。小小的挑战，另一端是值得期待的收获。",
    explore: "浏览挑战", how: "如何参与", board: "Bounty 任务板",
    boardTitle: "一个想法。一个期限。轮到你了。",
    open: "进行中", closed: "已截止", archive: "往期", brief: "查看挑战",
    quiet: "目前没有开放的 bounty。", quietBody: "回顾上一次挑战，加入社区，关注接下来的活动。",
    latest: "往期挑战", live: "等待挑战", reward: "奖励", tickets: "张大会门票",
    deadline: "提交截止时间", event: "活动", location: "线下 · UTEC Barranco，利马",
    challenge: "挑战内容", challengeIntro: "从想法到参赛作品，只需几步。",
    rewards: "五张门票。两种获奖方式。", speakers: "与这些人一起学习", speakersIntro: "AI Frontier Conf '26 演讲嘉宾。",
    eventLink: "了解大会", all: "全部 bounties", join: "加入 Discord",
    questions: "需要帮助？", questionsBody: "在 bounty 论坛提问。社区是一个很好的起点。",
    forum: "提出问题", closedTitle: "本次挑战已结束。",
    closedBody: "提交已截止。感谢所有动手创造并分享作品的人。",
    entry: "你的作品", signInBody: "使用 Crafter 账号登录后提交帖子。",
    signIn: "登录并参与", closingNote: "截止时间均为利马时间（UTC−5）。",
    howTitle: "从“如果……”到“看看这个”。",
    process: [
      { title: "选择挑战。", body: "阅读任务、奖励和截止时间。每个 bounty 都有自己的规则。" },
      { title: "做出你的风格。", body: "创造值得分享的作品，展示你的过程和成果。" },
      { title: "分享给大家。", body: "分享作品并在截止前提交。奖励分配方式以任务说明为准。" },
    ],
    invitation: "有人同行，创造更有趣。",
    invitationBody: "交流想法，听听另一种视角，认识和你一起动手创造的人。",
    attendance: "你需要能够到场参加。获奖公告原定于 10 月 5 日发布。",
  },
  ja: {
    eyebrow: "小さな挑戦。つくり始める、いいきっかけ。",
    description: "何かをつくり、コミュニティに共有して、その成果で挑戦しよう。小さなクエストの先に、新しい楽しみが待っています。",
    explore: "チャレンジを見る", how: "参加の流れ", board: "Bounty ボード",
    boardTitle: "アイデアと締め切り。次はあなたの番。",
    open: "募集中", closed: "締め切り", archive: "アーカイブ", brief: "詳細を見る",
    quiet: "現在募集中の bounty はありません。", quietBody: "前回の挑戦を振り返り、コミュニティで次の機会を見つけよう。",
    latest: "過去のチャレンジ", live: "チャレンジ募集中", reward: "報酬", tickets: "枚のカンファレンスチケット",
    deadline: "応募締め切り", event: "イベント", location: "現地参加 · UTEC Barranco、リマ",
    challenge: "チャレンジ", challengeIntro: "アイデアから応募まで、いくつかのステップ。",
    rewards: "5枚のチケット。2つのチャンス。", speakers: "学びを届ける人たち", speakersIntro: "AI Frontier Conf '26 の登壇者。",
    eventLink: "カンファレンスを見る", all: "すべての bounties", join: "Discord に参加",
    questions: "手助けが必要？", questionsBody: "Bounty フォーラムで質問しよう。コミュニティが出発点になります。",
    forum: "質問する", closedTitle: "今回の挑戦は終了しました。",
    closedBody: "応募は締め切りました。つくって、共有してくれた皆さんに感謝します。",
    entry: "あなたの応募", signInBody: "Crafter アカウントでログインして投稿を送信。",
    signIn: "ログインして参加", closingNote: "締め切りはすべてリマ時間（UTC−5）です。",
    howTitle: "「もしも」から「見て、できた」へ。",
    process: [
      { title: "挑戦を選ぶ。", body: "内容、報酬、締め切りを確認。Bounty ごとにルールがあります。" },
      { title: "自分らしくつくる。", body: "共有したくなるものをつくり、過程と成果を見せよう。" },
      { title: "世界に届ける。", body: "作品を共有して締め切り前に応募。報酬の選定方法は募集要項を確認。" },
    ],
    invitation: "仲間と一緒なら、もっと楽しい。",
    invitationBody: "アイデアを交換し、別の視点に出会い、一緒につくる人とつながろう。",
    attendance: "現地参加が条件です。当選者の発表は10月5日に予定されていました。",
  },
} as const

type Content = Pick<Bounty, "title" | "speakersNote" | "steps" | "rewards"> & { summary: string }
const frontierContent: Record<Locale, Content> = {
  es: {
    title: "5 entradas gratis para AI Frontier Conf '26",
    summary: "Construye con IA, muestra lo que hiciste y lleva tu curiosidad a la conferencia.",
    speakersNote: "Ignacio monta agentes autónomos en vivo en el Builder Track.",
    steps: ["Este finde construye algo con IA.", "Hazle un video con Opus 5.5.", "Postéalo en X, LinkedIn o IG etiquetando a @RaillyHugo y @crafterstation, con el link del evento.", "Manda el link de tu post aquí antes del lunes 5 de octubre a las 4 p. m. (hora Perú)."],
    rewards: ["3 entradas para los mejores posts.", "2 entradas sorteadas entre todos los que participen."],
  },
  en: {
    title: "5 free tickets to AI Frontier Conf '26",
    summary: "Build with AI, show what you made, and take your curiosity to the conference.",
    speakersNote: "Ignacio builds autonomous agents live in the Builder Track.",
    steps: ["Build something with AI over the weekend.", "Make a video about it with Opus 5.5.", "Post it on X, LinkedIn, or Instagram, tagging @RaillyHugo and @crafterstation and including the event link.", "Send your post link here before Monday, October 5 at 4 p.m. (Peru time)."],
    rewards: ["3 tickets for the best posts.", "2 tickets drawn among all participants."],
  },
  pt: {
    title: "5 ingressos grátis para a AI Frontier Conf '26",
    summary: "Crie com IA, mostre seu trabalho e leve sua curiosidade para a conferência.",
    speakersNote: "Ignacio cria agentes autônomos ao vivo no Builder Track.",
    steps: ["Crie algo com IA neste fim de semana.", "Faça um vídeo sobre isso com Opus 5.5.", "Publique no X, LinkedIn ou Instagram, marcando @RaillyHugo e @crafterstation e incluindo o link do evento.", "Envie o link do post aqui antes de segunda-feira, 5 de outubro, às 16h (horário do Peru)."],
    rewards: ["3 ingressos para os melhores posts.", "2 ingressos sorteados entre todos os participantes."],
  },
  zh: {
    title: "5 张 AI Frontier Conf '26 免费门票",
    summary: "用 AI 创造作品，展示你的成果，带着好奇心走进大会。",
    speakersNote: "Ignacio 将在 Builder Track 现场构建自主智能体。",
    steps: ["在周末用 AI 创造一个作品。", "用 Opus 5.5 为它制作一个视频。", "发布到 X、LinkedIn 或 Instagram，标记 @RaillyHugo 和 @crafterstation，并附上活动链接。", "在 10 月 5 日星期一下午 4 点（秘鲁时间）前，在这里提交帖子链接。"],
    rewards: ["3 张门票颁给最佳帖子。", "2 张门票从所有参与者中抽取。"],
  },
  ja: {
    title: "AI Frontier Conf '26 の無料チケット5枚",
    summary: "AI でつくり、成果を見せて、好奇心をカンファレンスへ持っていこう。",
    speakersNote: "Ignacio が Builder Track で自律エージェントをライブで構築します。",
    steps: ["週末に AI を使って何かをつくる。", "Opus 5.5 で紹介動画をつくる。", "X、LinkedIn、Instagram に投稿し、@RaillyHugo と @crafterstation をタグ付け。イベントのリンクも添える。", "10月5日（月）午後4時（ペルー時間）までに、ここで投稿リンクを送信する。"],
    rewards: ["優秀な投稿にチケット3枚。", "参加者全員から抽選でチケット2枚。"],
  },
}

export function bountyContent(bounty: Bounty, locale: Locale): Content {
  return bounty.slug === "1" ? frontierContent[locale] : { ...bounty, summary: bounty.prize }
}

export function bountyDate(value: string, locale: Locale, includeTime = true) {
  return new Intl.DateTimeFormat(locale, {
    timeZone: "America/Lima", day: "numeric", month: "short", year: "numeric",
    ...(includeTime ? { hour: "numeric", minute: "2-digit" } as const : {}),
  }).format(new Date(value))
}
