import type { Locale } from "@/lib/i18n"

export type MenuTranslations = Record<Exclude<Locale, "es">, Record<string, readonly [name: string, description: string]>>

// Menu names used for fulfillment remain in the Spanish source catalog.
// Each menu owns its translations so future venues may reuse item IDs safely.
export const donSalazarTranslations: MenuTranslations = {
  en: {
    espresso: ["Espresso", "One intensely flavored shot."],
    "espresso-doble": ["Double espresso", "Two intense shots."],
    americano: ["Americano", "Espresso and hot water."],
    macchiato: ["Macchiato", "Espresso with a touch of milk foam."],
    cortado: ["Cortado", "Espresso with a little milk."],
    cappuccino: ["Cappuccino", "Espresso, milk and dense foam."],
    latte: ["Latte", "Smooth espresso with plenty of milk."],
    "flat-white": ["Flat white", "Espresso and silky microfoam."],
    stumpy: ["Stumpy", "Concentrated espresso with a little microfoam."],
    mocaccino: ["Mochaccino", "Espresso, milk and chocolate."],
    "white-cappuccino": ["White cappuccino", "Cappuccino with vanilla."],
    "pink-cappuccino": ["Pink cappuccino", "Cappuccino with strawberry."],
    "black-cappuccino": ["Black cappuccino", "The house specialty."],
    ceremonia: ["Coffee ceremony", "Estate coffee brewed with V60, Origami, Chemex, Aeropress or Press2Go."],
    "americano-frio": ["Iced americano", "Espresso with ice and water."],
    "orange-coffee": ["Orange coffee", "Orange juice with a double cold-drip shot."],
    "iced-cappuccino": ["Iced cappuccino", "Espresso, milk and ice."],
    "cold-drip": ["Cold drip", "Cold-filtered for 8 hours."],
    "frappe-don-salazar": ["Don Salazar frappé", "The house specialty frappé."],
    "sparkling-clasico": ["Classic sparkling coffee", "Lime, coffee and ginger ale."],
    "iced-white-cappuccino": ["Iced white cappuccino", "With vanilla and ice."],
    "iced-pink-cappuccino": ["Iced pink cappuccino", "With strawberry and ice."],
    "frappe-oreo": ["Oreo frappé", "A specialty Oreo frappé."],
    "sparkling-maracumango": ["Maracumango sparkling coffee", "Passion fruit, mango, lime, coffee and ginger ale."],
    "iced-black-cappuccino": ["Iced black cappuccino", "The house specialty, over ice."],
    "sparkling-dragon": ["Dragon sparkling coffee", "Red berries, lime, coffee and ginger ale."],
    "jugo-naranja": ["Orange juice", "Freshly squeezed orange juice."],
    "alivio": ["Alivio Don Salazar", "A digestive herbal infusion."],
    "amor-jamaica": ["Amor de Jamaica", "A hot hibiscus infusion."],
    "evian-gas": ["Evian sparkling water", "330 ml."],
    evian: ["Evian still water", "500 ml."],
    chocolate: ["Hot chocolate", "Melted chocolate with milk."],
    "orange-fizz": ["Orange fizz", "A sparkling orange drink."],
    "tropical-fizz": ["Tropical fizz", "A sparkling tropical-fruit drink."],
    cerveza: ["Sol de la Finca beer", "The house craft beer."],
    galletas: ["Chocolate-chip cookie", "Large and soft."],
    brownie: ["Brownie", "With house-made fudge."],
    queque: ["House-made cake", "Flavor depends on availability."],
    "muffin-chocolate": ["Triple-chocolate muffin", "Intense cocoa flavor."],
    "muffin-queso": ["Cheese and blueberry muffin", "Cream cheese and blueberries."],
    "galleton-nutella": ["Large Nutella cookie", "Filled with Nutella."],
    "torta-chocolate": ["Chocolate cake", "Simply delicious."],
    affogato: ["Affogato Don Salazar", "Farm-made ice cream with espresso."],
    "cheesecake-maracumango": ["Maracumango cheesecake", "Passion fruit, mango and coconut."],
    "cheesecake-frutos-rojos": ["Red-berry cheesecake", "With fresh red berries."],
    "carrot-cake": ["Carrot cake", "A lovely carrot cake."],
    waffles: ["Farmhouse waffles", "Blueberries, strawberries and honey."],
    "empanada-carne": ["Prime-beef empanada", "Juicy beef filling."],
    "empanada-bechamel": ["Béchamel empanada", "Chicken, mushrooms and béchamel."],
    "empanada-napolitana": ["Neapolitan empanada", "Tomato, mozzarella, ham and basil."],
    "empanada-cheeseburger": ["Cheeseburger empanada", "Beef and cheese, burger style."],
    "sandwich-pollo": ["Chicken sandwich", "Chicken with house-made mayonnaise."],
    "croissant-mixto": ["Ham-and-cheese croissant", "Ham and Cajamarca cheese."],
    "mini-churros": ["5 mini churros", "Filled with cheese and ham."],
    "croissant-pollo": ["Chicken croissant", "Chicken with house-made mayonnaise."],
    toston: ["Avocado and chicken toast", "Country bread, avocado and chicken."],
    "focaccia-capresse": ["Caprese focaccia", "Tomato, mozzarella and basil."],
  },
  pt: {
    espresso: ["Espresso", "Uma dose de sabor intenso."],
    "espresso-doble": ["Espresso duplo", "Duas doses intensas."],
    americano: ["Americano", "Espresso com água quente."],
    macchiato: ["Macchiato", "Espresso com um toque de espuma de leite."],
    cortado: ["Cortado", "Espresso com um pouco de leite."],
    cappuccino: ["Cappuccino", "Espresso, leite e espuma densa."],
    latte: ["Latte", "Espresso suave com bastante leite."],
    "flat-white": ["Flat white", "Espresso com microespuma sedosa."],
    stumpy: ["Stumpy", "Espresso concentrado com pouca microespuma."],
    mocaccino: ["Mocaccino", "Espresso, leite e chocolate."],
    "white-cappuccino": ["White cappuccino", "Cappuccino com baunilha."],
    "pink-cappuccino": ["Pink cappuccino", "Cappuccino com morango."],
    "black-cappuccino": ["Black cappuccino", "A especialidade da casa."],
    ceremonia: ["Cerimônia do café", "Café de fazenda preparado no V60, Origami, Chemex, Aeropress ou Press2Go."],
    "americano-frio": ["Americano gelado", "Espresso com gelo e água."],
    "orange-coffee": ["Orange coffee", "Suco de laranja com dose dupla de cold drip."],
    "iced-cappuccino": ["Cappuccino gelado", "Espresso, leite e gelo."],
    "cold-drip": ["Cold drip", "Filtrado a frio por 8 horas."],
    "frappe-don-salazar": ["Frappé Don Salazar", "O frappé especial da casa."],
    "sparkling-clasico": ["Sparkling coffee clássico", "Limão, café e ginger ale."],
    "iced-white-cappuccino": ["White cappuccino gelado", "Com baunilha e gelo."],
    "iced-pink-cappuccino": ["Pink cappuccino gelado", "Com morango e gelo."],
    "frappe-oreo": ["Frappé de Oreo", "Um frappé especial de Oreo."],
    "sparkling-maracumango": ["Sparkling coffee maracumango", "Maracujá, manga, limão, café e ginger ale."],
    "iced-black-cappuccino": ["Black cappuccino gelado", "A especialidade da casa, com gelo."],
    "sparkling-dragon": ["Sparkling coffee dragon", "Frutas vermelhas, limão, café e ginger ale."],
    "jugo-naranja": ["Suco de laranja", "Laranja espremida na hora."],
    alivio: ["Alivio Don Salazar", "Infusão de ervas digestivas."],
    "amor-jamaica": ["Amor de Jamaica", "Infusão quente de hibisco."],
    "evian-gas": ["Água Evian com gás", "330 ml."],
    evian: ["Água Evian sem gás", "500 ml."],
    chocolate: ["Chocolate quente", "Chocolate derretido com leite."],
    "orange-fizz": ["Orange fizz", "Bebida gaseificada de laranja."],
    "tropical-fizz": ["Tropical fizz", "Bebida gaseificada de frutas tropicais."],
    cerveza: ["Cerveja Sol de la Finca", "A cerveja artesanal da casa."],
    galletas: ["Cookie com gotas de chocolate", "Grande e macio."],
    brownie: ["Brownie", "Com fudge caseiro."],
    queque: ["Bolo artesanal", "Sabor conforme a disponibilidade."],
    "muffin-chocolate": ["Muffin de chocolate triplo", "Sabor intenso de cacau."],
    "muffin-queso": ["Muffin de queijo e mirtilo", "Cream cheese e mirtilos."],
    "galleton-nutella": ["Cookie grande de Nutella", "Recheado com Nutella."],
    "torta-chocolate": ["Bolo de chocolate", "Simplesmente delicioso."],
    affogato: ["Affogato Don Salazar", "Sorvete da fazenda com espresso."],
    "cheesecake-maracumango": ["Cheesecake maracumango", "Maracujá, manga e coco."],
    "cheesecake-frutos-rojos": ["Cheesecake de frutas vermelhas", "Com frutas vermelhas frescas."],
    "carrot-cake": ["Bolo de cenoura", "Um belo bolo de cenoura."],
    waffles: ["Waffles da fazenda", "Mirtilos, morangos e mel."],
    "empanada-carne": ["Empanada de carne prime", "Recheio de carne bovina suculenta."],
    "empanada-bechamel": ["Empanada de béchamel", "Frango, cogumelos e molho béchamel."],
    "empanada-napolitana": ["Empanada napolitana", "Tomate, mozzarella, presunto e manjericão."],
    "empanada-cheeseburger": ["Empanada cheeseburger", "Carne e queijo, estilo hambúrguer."],
    "sandwich-pollo": ["Sanduíche de frango", "Frango com maionese caseira."],
    "croissant-mixto": ["Croissant de presunto e queijo", "Presunto e queijo de Cajamarca."],
    "mini-churros": ["5 mini churros", "Recheados com queijo e presunto."],
    "croissant-pollo": ["Croissant de frango", "Frango com maionese caseira."],
    toston: ["Torrada com abacate e frango", "Pão rústico, abacate e frango."],
    "focaccia-capresse": ["Focaccia caprese", "Tomate, mozzarella e manjericão."],
  },
  zh: {
    espresso: ["意式浓缩", "一份浓郁的浓缩咖啡。"],
    "espresso-doble": ["双份浓缩", "双份浓郁的浓缩咖啡。"],
    americano: ["美式咖啡", "浓缩咖啡加热水。"],
    macchiato: ["玛奇朵", "浓缩咖啡加少量奶泡。"],
    cortado: ["科尔塔多", "浓缩咖啡加少量牛奶。"],
    cappuccino: ["卡布奇诺", "浓缩咖啡、牛奶与绵密奶泡。"],
    latte: ["拿铁", "柔和的浓缩咖啡配足量牛奶。"],
    "flat-white": ["馥芮白", "浓缩咖啡配细腻奶泡。"],
    stumpy: ["Stumpy", "浓郁浓缩咖啡加少量细奶泡。"],
    mocaccino: ["摩卡", "浓缩咖啡、牛奶与巧克力。"],
    "white-cappuccino": ["香草卡布奇诺", "加入香草的卡布奇诺。"],
    "pink-cappuccino": ["草莓卡布奇诺", "加入草莓的卡布奇诺。"],
    "black-cappuccino": ["Black cappuccino", "店内招牌饮品。"],
    ceremonia: ["咖啡仪式", "庄园咖啡，可选 V60、Origami、Chemex、Aeropress 或 Press2Go 冲煮。"],
    "americano-frio": ["冰美式", "浓缩咖啡加冰块与水。"],
    "orange-coffee": ["橙汁咖啡", "橙汁配双份冰滴咖啡。"],
    "iced-cappuccino": ["冰卡布奇诺", "浓缩咖啡、牛奶与冰块。"],
    "cold-drip": ["冰滴咖啡", "低温滴滤 8 小时。"],
    "frappe-don-salazar": ["Don Salazar 冰沙", "店内招牌冰沙。"],
    "sparkling-clasico": ["经典气泡咖啡", "青柠、咖啡与姜汁汽水。"],
    "iced-white-cappuccino": ["冰香草卡布奇诺", "加入香草与冰块。"],
    "iced-pink-cappuccino": ["冰草莓卡布奇诺", "加入草莓与冰块。"],
    "frappe-oreo": ["奥利奥冰沙", "特色奥利奥冰沙。"],
    "sparkling-maracumango": ["百香芒果气泡咖啡", "百香果、芒果、青柠、咖啡与姜汁汽水。"],
    "iced-black-cappuccino": ["冰 Black cappuccino", "招牌饮品的冰饮版本。"],
    "sparkling-dragon": ["Dragon 气泡咖啡", "红色莓果、青柠、咖啡与姜汁汽水。"],
    "jugo-naranja": ["鲜榨橙汁", "现榨橙汁。"],
    alivio: ["Alivio Don Salazar", "助消化草本茶。"],
    "amor-jamaica": ["Amor de Jamaica", "热洛神花茶。"],
    "evian-gas": ["依云气泡水", "330 毫升。"],
    evian: ["依云矿泉水", "500 毫升。"],
    chocolate: ["热巧克力", "融化的巧克力与牛奶。"],
    "orange-fizz": ["橙味气泡饮", "橙味气泡饮品。"],
    "tropical-fizz": ["热带水果气泡饮", "热带水果风味气泡饮品。"],
    cerveza: ["Sol de la Finca 啤酒", "店内精酿啤酒。"],
    galletas: ["巧克力豆曲奇", "大块软曲奇。"],
    brownie: ["布朗尼", "配自制巧克力软糖酱。"],
    queque: ["手工蛋糕", "口味以当日供应为准。"],
    "muffin-chocolate": ["三重巧克力玛芬", "浓郁可可风味。"],
    "muffin-queso": ["芝士蓝莓玛芬", "奶油芝士与蓝莓。"],
    "galleton-nutella": ["大块 Nutella 曲奇", "榛子巧克力酱夹心。"],
    "torta-chocolate": ["巧克力蛋糕", "简单美味。"],
    affogato: ["Affogato Don Salazar", "庄园冰淇淋配浓缩咖啡。"],
    "cheesecake-maracumango": ["百香芒果芝士蛋糕", "百香果、芒果与椰子。"],
    "cheesecake-frutos-rojos": ["莓果芝士蛋糕", "配新鲜红色莓果。"],
    "carrot-cake": ["胡萝卜蛋糕", "美味的胡萝卜蛋糕。"],
    waffles: ["庄园华夫饼", "蓝莓、草莓与蜂蜜。"],
    "empanada-carne": ["优选牛肉馅饼", "多汁牛肉馅。"],
    "empanada-bechamel": ["白酱馅饼", "鸡肉、蘑菇与白酱。"],
    "empanada-napolitana": ["那不勒斯馅饼", "番茄、马苏里拉芝士、火腿与罗勒。"],
    "empanada-cheeseburger": ["芝士汉堡馅饼", "汉堡风味的牛肉与芝士。"],
    "sandwich-pollo": ["鸡肉三明治", "鸡肉配自制蛋黄酱。"],
    "croissant-mixto": ["火腿芝士可颂", "火腿与卡哈马卡芝士。"],
    "mini-churros": ["5 个迷你吉拿棒", "芝士与火腿夹心。"],
    "croissant-pollo": ["鸡肉可颂", "鸡肉配自制蛋黄酱。"],
    toston: ["牛油果鸡肉吐司", "乡村面包、牛油果与鸡肉。"],
    "focaccia-capresse": ["卡普雷塞佛卡夏", "番茄、马苏里拉芝士与罗勒。"],
  },
  ja: {
    espresso: ["エスプレッソ", "濃厚な味わいのワンショット。"],
    "espresso-doble": ["ダブルエスプレッソ", "濃厚なダブルショット。"],
    americano: ["アメリカーノ", "エスプレッソにお湯を加えて。"],
    macchiato: ["マキアート", "エスプレッソに少量のミルクフォーム。"],
    cortado: ["コルタード", "エスプレッソに少量のミルク。"],
    cappuccino: ["カプチーノ", "エスプレッソ、ミルク、きめ細かな泡。"],
    latte: ["ラテ", "まろやかなエスプレッソにたっぷりのミルク。"],
    "flat-white": ["フラットホワイト", "エスプレッソと滑らかなマイクロフォーム。"],
    stumpy: ["スタンピー", "濃いエスプレッソに少量のマイクロフォーム。"],
    mocaccino: ["モカチーノ", "エスプレッソ、ミルク、チョコレート。"],
    "white-cappuccino": ["ホワイトカプチーノ", "バニラ入りのカプチーノ。"],
    "pink-cappuccino": ["ピンクカプチーノ", "いちご入りのカプチーノ。"],
    "black-cappuccino": ["ブラックカプチーノ", "お店のスペシャリテ。"],
    ceremonia: ["コーヒーセレモニー", "農園のコーヒーを V60、Origami、Chemex、Aeropress、Press2Go で抽出。"],
    "americano-frio": ["アイスアメリカーノ", "エスプレッソに氷と水。"],
    "orange-coffee": ["オレンジコーヒー", "オレンジジュースにダブルの水出しコーヒー。"],
    "iced-cappuccino": ["アイスカプチーノ", "エスプレッソ、ミルク、氷。"],
    "cold-drip": ["コールドドリップ", "8 時間かけて低温抽出。"],
    "frappe-don-salazar": ["Don Salazar フラッペ", "お店自慢のフラッペ。"],
    "sparkling-clasico": ["クラシックスパークリングコーヒー", "ライム、コーヒー、ジンジャーエール。"],
    "iced-white-cappuccino": ["アイスホワイトカプチーノ", "バニラと氷入り。"],
    "iced-pink-cappuccino": ["アイスピンクカプチーノ", "いちごと氷入り。"],
    "frappe-oreo": ["オレオフラッペ", "特製オレオフラッペ。"],
    "sparkling-maracumango": ["マラクマンゴ・スパークリングコーヒー", "パッションフルーツ、マンゴー、ライム、コーヒー、ジンジャーエール。"],
    "iced-black-cappuccino": ["アイスブラックカプチーノ", "お店のスペシャリテをアイスで。"],
    "sparkling-dragon": ["ドラゴン・スパークリングコーヒー", "レッドベリー、ライム、コーヒー、ジンジャーエール。"],
    "jugo-naranja": ["オレンジジュース", "搾りたてのオレンジジュース。"],
    alivio: ["Alivio Don Salazar", "消化を助けるハーブティー。"],
    "amor-jamaica": ["Amor de Jamaica", "温かいハイビスカスティー。"],
    "evian-gas": ["エビアン炭酸水", "330 ml。"],
    evian: ["エビアン", "500 ml。"],
    chocolate: ["ホットチョコレート", "溶かしたチョコレートとミルク。"],
    "orange-fizz": ["オレンジフィズ", "オレンジの炭酸ドリンク。"],
    "tropical-fizz": ["トロピカルフィズ", "トロピカルフルーツの炭酸ドリンク。"],
    cerveza: ["Sol de la Finca ビール", "お店のクラフトビール。"],
    galletas: ["チョコチップクッキー", "大きくて柔らかいクッキー。"],
    brownie: ["ブラウニー", "自家製ファッジ添え。"],
    queque: ["手作りケーキ", "フレーバーは当日の用意によります。"],
    "muffin-chocolate": ["トリプルチョコレートマフィン", "濃厚なカカオの味わい。"],
    "muffin-queso": ["チーズとブルーベリーのマフィン", "クリームチーズとブルーベリー。"],
    "galleton-nutella": ["大きな Nutella クッキー", "ヌテラ入り。"],
    "torta-chocolate": ["チョコレートケーキ", "シンプルなおいしさ。"],
    affogato: ["Affogato Don Salazar", "農園のアイスクリームにエスプレッソ。"],
    "cheesecake-maracumango": ["マラクマンゴ・チーズケーキ", "パッションフルーツ、マンゴー、ココナッツ。"],
    "cheesecake-frutos-rojos": ["レッドベリーチーズケーキ", "新鮮なレッドベリー添え。"],
    "carrot-cake": ["キャロットケーキ", "おいしいキャロットケーキ。"],
    waffles: ["農園のワッフル", "ブルーベリー、いちご、はちみつ。"],
    "empanada-carne": ["プライムビーフのエンパナーダ", "ジューシーな牛肉入り。"],
    "empanada-bechamel": ["ベシャメルのエンパナーダ", "チキン、きのこ、ベシャメルソース。"],
    "empanada-napolitana": ["ナポリ風エンパナーダ", "トマト、モッツァレラ、ハム、バジル。"],
    "empanada-cheeseburger": ["チーズバーガー・エンパナーダ", "バーガー風の牛肉とチーズ。"],
    "sandwich-pollo": ["チキンサンドイッチ", "チキンと自家製マヨネーズ。"],
    "croissant-mixto": ["ハムとチーズのクロワッサン", "ハムとカハマルカのチーズ。"],
    "mini-churros": ["ミニチュロス 5 個", "チーズとハム入り。"],
    "croissant-pollo": ["チキンクロワッサン", "チキンと自家製マヨネーズ。"],
    toston: ["アボカドとチキンのトースト", "田舎パン、アボカド、チキン。"],
    "focaccia-capresse": ["カプレーゼ・フォカッチャ", "トマト、モッツァレラ、バジル。"],
  },
}
