import type { Locale } from "@/lib/i18n"

const en = {
  agenda: "Agenda", eyebrow: "Codex community · Lima", city: "An evening to build together.",
  intro: "A DevDay recap, ideas and hands-on building with Codex. An independent community gathering at FISI–UNMSM.",
  date: "October 21, 2026", format: "In person · Free · In Spanish",
  request: "Request a spot on Luma", access: "Complete my entry details", approvedLink: "Already accepted?",
  flowTitle: "Your place, step by step.",
  steps: ["Apply on Luma", "Wait for your acceptance", "Complete your entry details"],
  stepBodies: ["Registration and selection happen on Luma.", "Your Luma status must be approved to continue.", "Sign in to Crafter with the same email and tell us what you are bringing."],
  bring: "Bring your laptop, charger and an idea.",
  bringBody: "No competition or required presentations. We’ll recap DevDay, build together and leave time for feedback.",
  disclaimer: "An independent event organized by the local community.",
  entry: "Ready to join us?", entryIntro: "If your spot is approved on Luma, complete the information needed to coordinate your entry to the venue.",
  deadline: "You can save or update your details until", lima: "Lima time",
  signInTitle: "First, your Crafter account.", signInBody: "Sign in or create an account with the email you used on Luma. We’ll check your acceptance before asking for your entry details.", signIn: "Sign in or create an account",
  pendingTitle: "Your spot is not approved yet.", pendingBody: "These details are only needed after your application is accepted. Check your status on Luma, or link another verified email if you applied with one.",
  missingTitle: "We couldn’t find your registration.", missingBody: "Use the same email as your Luma application. You can verify another email on this account below.",
  unavailableTitle: "We can’t check your spot right now.", unavailableBody: "Please try again later. Your information hasn’t been submitted.",
  retry: "Check again", closedTitle: "Entry registration is closed.", closedBody: "The deadline to submit or edit entry details has passed.", viewEvent: "Back to the event",
  formTitle: "Your entry details", approved: "Luma registration approved", fullName: "Full legal name", documentType: "Document type", documentNumber: "Document number",
  dni: "DNI", foreign: "Foreign resident ID", passport: "Passport",
  documentHint: "DNI: 8 digits. Other documents: 6–20 letters or numbers. Do not upload a photo.",
  hasVehicle: "I’m bringing a vehicle", plate: "Vehicle plate", equipment: "Equipment you’re bringing", equipmentHint: "One item per line: type, brand and model. Include your laptop and any other equipment.", noEquipment: "I’m not bringing equipment",
  privacyTitle: "Only for your entry to this event.",
  privacy: "The organizers will use these details to coordinate access with venue staff. They won’t appear on your public Crafter profile.",
  consent: "I confirm these details are correct and authorize their use to coordinate my entry to this event.",
  save: "Save entry details", update: "Update entry details", saving: "Saving…", saved: "Your entry details are saved.", savedBody: "You can update them until the deadline. Your acceptance and ticket remain on Luma.",
  errors: { closed: "The submission deadline has passed.", auth: "Sign in again to continue.", approval: "Your registration must be approved on Luma.", unavailable: "We couldn’t save your details. Please try again later.", invalid: "Check the highlighted fields and confirm the use of your details." },
  fieldError: "Please check this field.", admin: "Event entry", export: "Download accepted attendees CSV", empty: "No entry details have been submitted.", email: "Email", status: "Luma status", updated: "Updated", adminUnavailable: "The entry list or Luma verification is temporarily unavailable.", notApproved: "Not approved", verified: "Approved", unverified: "Not verified",
  adminHelp: "Acceptance is checked again before export. Only currently approved attendees are included. Keep the downloaded file private and share it only with the people coordinating venue access.",
}
type Copy = { [K in keyof typeof en]: typeof en[K] extends string ? string : typeof en[K] extends string[] ? string[] : Record<keyof typeof en.errors, string> }

export const eventAccessCopy: Record<Locale, Copy> = {
  en,
  es: {
    agenda: "Agenda", eyebrow: "Comunidad Codex · Lima", city: "Una tarde para construir juntos.",
    intro: "Un repaso de DevDay, ideas y manos al código con Codex. Un encuentro independiente de la comunidad en FISI–UNMSM.",
    date: "21 de octubre de 2026", format: "Presencial · Gratis · En español",
    request: "Solicitar un lugar en Luma", access: "Completar mis datos de ingreso", approvedLink: "¿Ya te aceptaron?",
    flowTitle: "Tu lugar, paso a paso.", steps: ["Postula en Luma", "Espera tu aceptación", "Completa tus datos de ingreso"],
    stepBodies: ["El registro y la selección se hacen en Luma.", "Tu registro debe estar aprobado en Luma para continuar.", "Entra a Crafter con el mismo correo y cuéntanos qué llevarás."],
    bring: "Trae tu laptop, cargador y una idea.", bringBody: "Sin competencia ni presentaciones obligatorias. Repasamos DevDay, construimos juntos y cerramos compartiendo feedback.",
    disclaimer: "Un evento independiente organizado por la comunidad local.",
    entry: "¿Listo para encontrarnos?", entryIntro: "Si ya te aceptaron en Luma, completa la información que necesitamos para coordinar tu ingreso al local.",
    deadline: "Puedes guardar o actualizar tus datos hasta el", lima: "hora de Lima",
    signInTitle: "Primero, tu cuenta de Crafter.", signInBody: "Entra o crea una cuenta con el correo que usaste en Luma. Verificaremos tu aceptación antes de pedir tus datos de ingreso.", signIn: "Entrar o crear mi cuenta",
    pendingTitle: "Tu lugar aún no está aprobado.", pendingBody: "Solo necesitamos estos datos después de que acepten tu solicitud. Revisa tu estado en Luma o vincula otro correo verificado si postulaste con él.",
    missingTitle: "No encontramos tu registro.", missingBody: "Usa el mismo correo de tu postulación en Luma. Abajo puedes verificar otro correo en esta cuenta.",
    unavailableTitle: "Ahora no podemos verificar tu lugar.", unavailableBody: "Vuelve a intentarlo en un momento. No se han enviado tus datos.",
    retry: "Volver a verificar", closedTitle: "El registro de ingreso está cerrado.", closedBody: "Ya pasó el plazo para enviar o editar los datos de ingreso.", viewEvent: "Volver al evento",
    formTitle: "Tus datos de ingreso", approved: "Registro aprobado en Luma", fullName: "Nombres y apellidos completos", documentType: "Tipo de documento", documentNumber: "Número de documento",
    dni: "DNI", foreign: "Carné de extranjería", passport: "Pasaporte",
    documentHint: "DNI: 8 dígitos. Otros documentos: entre 6 y 20 letras o números. No subas una foto.",
    hasVehicle: "Iré en vehículo", plate: "Placa del vehículo", equipment: "Equipos que llevarás", equipmentHint: "Un equipo por línea: tipo, marca y modelo. Incluye tu laptop y cualquier otro equipo.", noEquipment: "No llevaré equipos",
    privacyTitle: "Solo para tu ingreso a este evento.",
    privacy: "La organización usará estos datos para coordinar el acceso con el personal del local. No aparecerán en tu perfil público de Crafter.",
    consent: "Confirmo que estos datos son correctos y autorizo su uso para coordinar mi ingreso a este evento.",
    save: "Guardar mis datos de ingreso", update: "Actualizar mis datos de ingreso", saving: "Guardando…", saved: "Tus datos de ingreso están guardados.", savedBody: "Puedes actualizarlos hasta el cierre. Tu aceptación y tu entrada siguen en Luma.",
    errors: { closed: "Ya cerró el plazo para enviar datos.", auth: "Vuelve a iniciar sesión para continuar.", approval: "Tu registro debe estar aprobado en Luma.", unavailable: "No pudimos guardar tus datos. Inténtalo en un momento.", invalid: "Revisa los campos señalados y confirma el uso de tus datos." },
    fieldError: "Revisa este campo.", admin: "Ingreso a eventos", export: "Descargar CSV de aceptados", empty: "Todavía no se enviaron datos de ingreso.", email: "Correo", status: "Estado en Luma", updated: "Actualizado", adminUnavailable: "La lista o la verificación de Luma no están disponibles por el momento.", notApproved: "Sin aprobación", verified: "Aprobado", unverified: "Sin verificar",
    adminHelp: "La aceptación se vuelve a verificar antes de exportar. Solo se incluyen personas aprobadas en ese momento. Mantén el archivo privado y compártelo solo con quienes coordinan el ingreso al local.",
  },
  pt: {
    agenda: "Agenda", eyebrow: "Comunidade Codex · Lima", city: "Uma tarde para construir juntos.",
    intro: "Um resumo do DevDay, ideias e prática com Codex. Um encontro independente da comunidade na FISI–UNMSM.",
    date: "21 de outubro de 2026", format: "Presencial · Gratuito · Em espanhol",
    request: "Solicitar uma vaga no Luma", access: "Preencher meus dados de entrada", approvedLink: "Já foi aceito?",
    flowTitle: "Sua vaga, passo a passo.", steps: ["Inscreva-se no Luma", "Aguarde sua aprovação", "Preencha seus dados de entrada"],
    stepBodies: ["A inscrição e a seleção acontecem no Luma.", "Sua inscrição precisa estar aprovada no Luma para continuar.", "Entre no Crafter com o mesmo e-mail e conte o que vai levar."],
    bring: "Traga seu laptop, carregador e uma ideia.", bringBody: "Sem competição ou apresentações obrigatórias. Vamos rever o DevDay, construir juntos e compartilhar feedback.",
    disclaimer: "Um evento independente organizado pela comunidade local.",
    entry: "Tudo pronto para o encontro?", entryIntro: "Se sua vaga foi aprovada no Luma, preencha os dados necessários para organizar sua entrada no local.",
    deadline: "Você pode salvar ou atualizar seus dados até", lima: "horário de Lima",
    signInTitle: "Primeiro, sua conta no Crafter.", signInBody: "Entre ou crie uma conta com o e-mail usado no Luma. Vamos verificar sua aprovação antes de pedir os dados de entrada.", signIn: "Entrar ou criar minha conta",
    pendingTitle: "Sua vaga ainda não foi aprovada.", pendingBody: "Estes dados só são necessários após a aprovação. Confira seu status no Luma ou vincule outro e-mail verificado se o usou na inscrição.",
    missingTitle: "Não encontramos sua inscrição.", missingBody: "Use o mesmo e-mail da inscrição no Luma. Você pode verificar outro e-mail nesta conta abaixo.",
    unavailableTitle: "Não podemos verificar sua vaga agora.", unavailableBody: "Tente novamente em instantes. Seus dados não foram enviados.",
    retry: "Verificar novamente", closedTitle: "O cadastro de entrada está encerrado.", closedBody: "O prazo para enviar ou editar os dados terminou.", viewEvent: "Voltar ao evento",
    formTitle: "Seus dados de entrada", approved: "Inscrição aprovada no Luma", fullName: "Nome completo conforme documento", documentType: "Tipo de documento", documentNumber: "Número do documento",
    dni: "DNI", foreign: "Documento de estrangeiro", passport: "Passaporte", documentHint: "DNI: 8 dígitos. Outros documentos: 6–20 letras ou números. Não envie foto.",
    hasVehicle: "Vou de veículo", plate: "Placa do veículo", equipment: "Equipamentos que vai levar", equipmentHint: "Um item por linha: tipo, marca e modelo. Inclua o laptop e outros equipamentos.", noEquipment: "Não levarei equipamentos",
    privacyTitle: "Somente para sua entrada neste evento.", privacy: "A organização usará estes dados para coordenar o acesso com a equipe do local. Eles não aparecerão no seu perfil público do Crafter.",
    consent: "Confirmo que os dados estão corretos e autorizo seu uso para coordenar minha entrada neste evento.",
    save: "Salvar meus dados de entrada", update: "Atualizar meus dados de entrada", saving: "Salvando…", saved: "Seus dados de entrada foram salvos.", savedBody: "Você pode atualizá-los até o prazo. Sua aprovação e seu ingresso continuam no Luma.",
    errors: { closed: "O prazo para enviar dados terminou.", auth: "Entre novamente para continuar.", approval: "Sua inscrição precisa estar aprovada no Luma.", unavailable: "Não conseguimos salvar. Tente novamente mais tarde.", invalid: "Confira os campos destacados e confirme o uso dos dados." },
    fieldError: "Confira este campo.", admin: "Entrada em eventos", export: "Baixar CSV de aprovados", empty: "Nenhum dado de entrada foi enviado.", email: "E-mail", status: "Status no Luma", updated: "Atualizado", adminUnavailable: "A lista ou a verificação do Luma está temporariamente indisponível.", notApproved: "Sem aprovação", verified: "Aprovado", unverified: "Não verificado",
    adminHelp: "A aprovação é verificada novamente antes da exportação. Apenas pessoas aprovadas no momento são incluídas. Mantenha o arquivo privado e compartilhe apenas com quem coordena a entrada.",
  },
  zh: {
    agenda: "活动", eyebrow: "Codex 社区 · 利马", city: "一起动手创造的夜晚。",
    intro: "回顾 DevDay，交流想法，用 Codex 动手构建。社区在 FISI–UNMSM 独立组织的聚会。",
    date: "2026年10月21日", format: "线下 · 免费 · 西班牙语",
    request: "在 Luma 申请名额", access: "填写入场信息", approvedLink: "已经获批？",
    flowTitle: "一步步确认你的参与。", steps: ["在 Luma 报名", "等待审核通过", "填写入场信息"],
    stepBodies: ["报名和筛选在 Luma 进行。", "Luma 报名获批后才能继续。", "使用同一邮箱登录 Crafter，并告知你将携带的设备。"],
    bring: "带上笔记本电脑、充电器和一个想法。", bringBody: "没有比赛或强制演示。我们将回顾 DevDay，一起构建并交流反馈。",
    disclaimer: "由本地社区独立组织的活动。",
    entry: "准备好见面了吗？", entryIntro: "如果你的 Luma 报名已获批，请填写协调场地入场所需的信息。",
    deadline: "保存或修改信息的截止时间：", lima: "利马时间",
    signInTitle: "先登录你的 Crafter 账户。", signInBody: "使用在 Luma 报名的邮箱登录或注册。我们会先验证报名获批状态，再请你填写入场信息。", signIn: "登录或创建账户",
    pendingTitle: "你的报名尚未获批。", pendingBody: "只有报名获批后才需要这些信息。请在 Luma 查看状态；如果使用了另一邮箱，请验证并关联该邮箱。",
    missingTitle: "未找到你的报名。", missingBody: "请使用 Luma 报名时的邮箱。你可以在下方为此账户验证另一个邮箱。",
    unavailableTitle: "暂时无法验证你的报名。", unavailableBody: "请稍后重试。你的信息尚未提交。",
    retry: "重新验证", closedTitle: "入场信息登记已截止。", closedBody: "提交或修改入场信息的时间已过。", viewEvent: "返回活动",
    formTitle: "你的入场信息", approved: "Luma 报名已获批", fullName: "证件上的完整姓名", documentType: "证件类型", documentNumber: "证件号码",
    dni: "DNI", foreign: "外国人居留证", passport: "护照", documentHint: "DNI：8位数字。其他证件：6–20位字母或数字。请勿上传证件照片。",
    hasVehicle: "我将驾车前往", plate: "车牌号码", equipment: "携带的设备", equipmentHint: "每行一个设备：类型、品牌和型号。请包括笔记本电脑及其他设备。", noEquipment: "我不携带设备",
    privacyTitle: "仅用于本次活动入场。", privacy: "组织者将使用这些信息与场地工作人员协调入场。这些信息不会显示在你的 Crafter 公开资料中。",
    consent: "我确认信息正确，并授权将其用于协调本次活动入场。",
    save: "保存入场信息", update: "更新入场信息", saving: "正在保存…", saved: "入场信息已保存。", savedBody: "截止时间前可以修改。你的报名状态和门票仍在 Luma。",
    errors: { closed: "信息提交已截止。", auth: "请重新登录以继续。", approval: "你的报名必须先在 Luma 获批。", unavailable: "无法保存信息，请稍后重试。", invalid: "请检查标出的字段，并确认信息使用授权。" },
    fieldError: "请检查此字段。", admin: "活动入场", export: "下载获批名单 CSV", empty: "尚无人提交入场信息。", email: "邮箱", status: "Luma 状态", updated: "更新时间", adminUnavailable: "名单或 Luma 验证暂时不可用。", notApproved: "未获批", verified: "已获批", unverified: "未验证",
    adminHelp: "导出前会重新验证报名状态，仅包含当时获批的参与者。请妥善保管文件，仅与负责场地入场的人员共享。",
  },
  ja: {
    agenda: "イベント", eyebrow: "Codex コミュニティ · リマ", city: "一緒につくる夕べ。",
    intro: "DevDay を振り返り、アイデアを共有し、Codex で開発。FISI–UNMSM でコミュニティが自主開催する集まりです。",
    date: "2026年10月21日", format: "現地開催 · 無料 · スペイン語",
    request: "Luma で参加申請", access: "入場情報を入力", approvedLink: "承認済みですか？",
    flowTitle: "参加までの流れ。", steps: ["Luma で申し込む", "承認を待つ", "入場情報を入力する"],
    stepBodies: ["申し込みと選考は Luma で行います。", "Luma で承認されると次に進めます。", "同じメールで Crafter にログインし、持参する機器を登録してください。"],
    bring: "ノートPC、充電器、アイデアを持って。", bringBody: "競争や必須の発表はありません。DevDay を振り返り、一緒に開発してフィードバックを共有します。",
    disclaimer: "地域コミュニティが自主開催するイベントです。",
    entry: "会う準備はできましたか？", entryIntro: "Luma で承認された方は、会場への入場手配に必要な情報を入力してください。",
    deadline: "情報の保存・変更期限：", lima: "リマ時間",
    signInTitle: "まず Crafter アカウントでログイン。", signInBody: "Luma で使ったメールでログインまたは登録してください。承認を確認してから入場情報をお伺いします。", signIn: "ログイン・アカウント作成",
    pendingTitle: "参加はまだ承認されていません。", pendingBody: "入場情報が必要になるのは承認後です。Luma で状況を確認するか、申し込みに使った別のメールを認証して追加してください。",
    missingTitle: "申し込みが見つかりませんでした。", missingBody: "Luma の申し込みと同じメールを使用してください。下で別のメールをこのアカウントに追加・認証できます。",
    unavailableTitle: "現在、参加状況を確認できません。", unavailableBody: "時間をおいてお試しください。情報はまだ送信されていません。",
    retry: "再確認する", closedTitle: "入場情報の登録は終了しました。", closedBody: "情報の送信・変更期限を過ぎています。", viewEvent: "イベントに戻る",
    formTitle: "入場情報", approved: "Luma で承認済み", fullName: "身分証明書の氏名", documentType: "証明書の種類", documentNumber: "証明書番号",
    dni: "DNI", foreign: "外国人居住証", passport: "パスポート", documentHint: "DNI：8桁の数字。他の証明書：6〜20文字の英数字。写真のアップロードは不要です。",
    hasVehicle: "車で来場する", plate: "車両ナンバー", equipment: "持参する機器", equipmentHint: "1行に1台、種類・メーカー・型番を入力。ノートPCや他の機器も含めてください。", noEquipment: "機器は持参しない",
    privacyTitle: "このイベントへの入場のためだけに。",
    privacy: "主催者が会場スタッフと入場を調整するために使用します。Crafter の公開プロフィールには表示されません。",
    consent: "情報が正しいことを確認し、このイベントへの入場調整に使用することに同意します。",
    save: "入場情報を保存", update: "入場情報を更新", saving: "保存中…", saved: "入場情報を保存しました。", savedBody: "期限までは変更できます。承認状況とチケットは引き続き Luma で確認してください。",
    errors: { closed: "送信期限を過ぎています。", auth: "再度ログインしてください。", approval: "Luma での承認が必要です。", unavailable: "保存できませんでした。後でもう一度お試しください。", invalid: "表示された項目と情報利用への同意を確認してください。" },
    fieldError: "この項目を確認してください。", admin: "イベント入場", export: "承認済み参加者の CSV をダウンロード", empty: "入場情報はまだありません。", email: "メール", status: "Luma の状態", updated: "更新日時", adminUnavailable: "名簿または Luma の確認が一時的に利用できません。", notApproved: "未承認", verified: "承認済み", unverified: "未確認",
    adminHelp: "出力前に承認状況を再確認し、その時点で承認済みの方だけを含めます。ファイルは非公開で保管し、入場調整の担当者だけと共有してください。",
  },
}
