import type { Locale } from "@/lib/i18n"

const en = {
  badge: "Preview", lensHint: "Move across the letters to see how they are drawn.",
  guides: { ascender: "ascender", capHeight: "cap height", xHeight: "x-height", baseline: "baseline" },
  sizesLabel: "One letter, two sizes", sizesTitle: "Same drawing. Tuned for where you read it.",
  sizesBody: "Crafter Sans is one typeface. Display is the original drawing, for headlines. Text is derived from it, with adjusted contours and more space so it holds up at 16 and 18 px.",
  displayCut: "Display · 500", textCut: "Text · 500", atSize: "at",
  bucleLabel: "The loop", bucleTitle: "Built in the open, one version at a time.",
  bucleBody: "Every release redraws something. The previous build sits in gold under the current one.",
  overlay: "Overlay", wipe: "Wipe", compare: "Compare", points: "points", pointsLegend: "Squares are on-curve nodes, circles are handles. The number is the point count.", editSample: "Your sample",
  entries: {
    xyz: { title: "x, y and z get their own masters.", body: "All 26 lowercase letters now come from cubic masters. This is how x, y and z changed in Bold." },
    kvw: { title: "k, v and w, redrawn.", body: "Cleaner Bold k corners, and a higher k anchor so its accents clear the letter." },
    ijl: { title: "i, j and l join the masters.", body: "Exact cubic geometry and round endpoint dots, in all four weights." },
    ft: { title: "Accents stop crashing into f and t.", body: "The top anchors move up, resolving 63 collisions between f, t and their marks." },
    display: { title: "Display finds its gesture.", body: "The second drawing of the original headline cut, the one the whole family grows from." },
  },
  legendTitle: "Where each character stands",
  master: "Cubic master", derived: "Derived from Display", pending: "Uppercase masters are next.",
  followLabel: "In progress", followTitle: "Follow the loop.",
  followBody: "Crafter Sans is still being drawn. It is not released for download yet; every new version lands here first.",
  github: "Crafter Station on GitHub", journal: "Read the journal",
  ticker: ["Built in the open", "Lima", "Bogotá", "Madrid", "1,000+ builders", "Craft. Ship. Repeat."],
}

export type BucleCopy = typeof en

export const bucleCopy: Record<Locale, BucleCopy> = {
  en,
  es: {
    badge: "Preview", lensHint: "Pasa el cursor sobre las letras para ver cómo están dibujadas.",
    guides: { ascender: "ascendente", capHeight: "altura de mayúsculas", xHeight: "altura de x", baseline: "línea base" },
    sizesLabel: "Una letra, dos tamaños", sizesTitle: "El mismo dibujo, ajustado a donde lo lees.",
    sizesBody: "Crafter Sans es una sola tipografía. Display es el dibujo original, para títulos. Text deriva de él, con contornos ajustados y más aire para que se lea bien a 16 y 18 px.",
    displayCut: "Display · 500", textCut: "Text · 500", atSize: "a",
    bucleLabel: "El bucle", bucleTitle: "Construida en público, una versión a la vez.",
    bucleBody: "Cada versión redibuja algo. La versión anterior queda en dorado, debajo de la actual.",
    overlay: "Superponer", wipe: "Deslizar", compare: "Comparar", points: "puntos", pointsLegend: "Los cuadrados son nodos, los círculos son manijas. El número es la cantidad de puntos.", editSample: "Tu muestra",
    entries: {
      xyz: { title: "x, y y z tienen su propio master.", body: "Las 26 minúsculas ya salen de masters cúbicos. Así cambiaron la x, la y y la z en Bold." },
      kvw: { title: "k, v y w, redibujadas.", body: "Esquinas más limpias en la k Bold y un anchor más alto para que sus acentos no toquen la letra." },
      ijl: { title: "i, j y l se suman a los masters.", body: "Geometría cúbica exacta y puntos redondos en los extremos, en los cuatro pesos." },
      ft: { title: "Los acentos dejan de chocar con la f y la t.", body: "Los anchors superiores suben y resuelven 63 colisiones entre f, t y sus marcas." },
      display: { title: "Display encuentra su gesto.", body: "El segundo dibujo del corte original para títulos, del que crece toda la familia." },
    },
    legendTitle: "En qué estado está cada carácter",
    master: "Master cúbico", derived: "Derivado de Display", pending: "Las mayúsculas son lo siguiente.",
    followLabel: "En proceso", followTitle: "Sigue el bucle.",
    followBody: "Crafter Sans todavía se está dibujando. Aún no se publica para descarga; cada versión nueva llega primero aquí.",
    github: "Crafter Station en GitHub", journal: "Leer el journal",
    ticker: ["Construida en público", "Lima", "Bogotá", "Madrid", "1,000+ builders", "Craft. Ship. Repeat."],
  },
  pt: {
    badge: "Preview", lensHint: "Passe o cursor sobre as letras para ver como são desenhadas.",
    guides: { ascender: "ascendente", capHeight: "altura das maiúsculas", xHeight: "altura de x", baseline: "linha de base" },
    sizesLabel: "Uma letra, dois tamanhos", sizesTitle: "O mesmo desenho, ajustado para onde você lê.",
    sizesBody: "Crafter Sans é uma só tipografia. Display é o desenho original, para títulos. Text deriva dele, com contornos ajustados e mais espaço para funcionar bem em 16 e 18 px.",
    displayCut: "Display · 500", textCut: "Text · 500", atSize: "em",
    bucleLabel: "O ciclo", bucleTitle: "Construída em público, uma versão por vez.",
    bucleBody: "Cada versão redesenha algo. A versão anterior fica em dourado, por baixo da atual.",
    overlay: "Sobrepor", wipe: "Deslizar", compare: "Comparar", points: "pontos", pointsLegend: "Quadrados são nós, círculos são alças. O número é a quantidade de pontos.", editSample: "Sua amostra",
    entries: {
      xyz: { title: "x, y e z ganham seus próprios masters.", body: "As 26 minúsculas agora vêm de masters cúbicos. Assim mudaram x, y e z no Bold." },
      kvw: { title: "k, v e w, redesenhadas.", body: "Cantos mais limpos no k Bold e uma âncora mais alta para os acentos não tocarem a letra." },
      ijl: { title: "i, j e l entram nos masters.", body: "Geometria cúbica exata e pontos redondos nas pontas, nos quatro pesos." },
      ft: { title: "Os acentos param de colidir com f e t.", body: "As âncoras superiores sobem e resolvem 63 colisões entre f, t e suas marcas." },
      display: { title: "Display encontra seu gesto.", body: "O segundo desenho do corte original para títulos, do qual cresce toda a família." },
    },
    legendTitle: "Em que estado está cada caractere",
    master: "Master cúbico", derived: "Derivado de Display", pending: "As maiúsculas são as próximas.",
    followLabel: "Em andamento", followTitle: "Acompanhe o ciclo.",
    followBody: "Crafter Sans ainda está sendo desenhada. Ainda não está disponível para download; cada nova versão chega aqui primeiro.",
    github: "Crafter Station no GitHub", journal: "Ler o journal",
    ticker: ["Construída em público", "Lima", "Bogotá", "Madrid", "1,000+ builders", "Craft. Ship. Repeat."],
  },
  zh: {
    badge: "预览", lensHint: "将光标移过字母，查看它们的绘制方式。",
    guides: { ascender: "上伸部", capHeight: "大写高度", xHeight: "x 高度", baseline: "基线" },
    sizesLabel: "同一字体，两种尺寸", sizesTitle: "同样的字形，为阅读场景而调整。",
    sizesBody: "Crafter Sans 是一款字体。Display 是原始字形，用于标题。Text 由它衍生，调整了轮廓并增加间距，在 16 和 18 px 下依然清晰。",
    displayCut: "Display · 500", textCut: "Text · 500", atSize: "@",
    bucleLabel: "循环", bucleTitle: "公开打造，一次一个版本。",
    bucleBody: "每个版本都会重绘一些字形。上一版本以金色显示在当前版本下方。",
    overlay: "叠加", wipe: "滑动", compare: "对比", points: "个点", pointsLegend: "方块是节点，圆点是控制柄。数字为点的数量。", editSample: "你的示例",
    entries: {
      xyz: { title: "x、y、z 拥有了自己的母版。", body: "26 个小写字母现在全部来自三次曲线母版。这是 Bold 中 x、y、z 的变化。" },
      kvw: { title: "重绘 k、v、w。", body: "Bold k 的拐角更干净，k 的锚点更高，重音符号不再碰到字母。" },
      ijl: { title: "i、j、l 加入母版。", body: "四种字重都使用精确的三次曲线和圆形端点。" },
      ft: { title: "重音符号不再与 f 和 t 相撞。", body: "上方锚点上移，解决了 f、t 与其符号之间的 63 处碰撞。" },
      display: { title: "Display 找到了它的笔触。", body: "原始标题字体的第二版字形，整个家族由此生长。" },
    },
    legendTitle: "每个字符的状态",
    master: "三次曲线母版", derived: "源自 Display", pending: "下一步是大写字母母版。",
    followLabel: "进行中", followTitle: "关注这个循环。",
    followBody: "Crafter Sans 仍在绘制中，暂未开放下载。每个新版本都会首先在这里发布。",
    github: "GitHub 上的 Crafter Station", journal: "阅读 Journal",
    ticker: ["公开打造", "Lima", "Bogotá", "Madrid", "1,000+ builders", "Craft. Ship. Repeat."],
  },
  ja: {
    badge: "プレビュー", lensHint: "文字の上でカーソルを動かすと、描画の構造が見えます。",
    guides: { ascender: "アセンダー", capHeight: "キャップハイト", xHeight: "xハイト", baseline: "ベースライン" },
    sizesLabel: "ひとつの書体、ふたつのサイズ", sizesTitle: "同じ描画を、読む場所に合わせて。",
    sizesBody: "Crafter Sans はひとつの書体です。Display は見出し用の元の描画。Text はそこから派生し、輪郭と字間を調整して 16・18 px でも読みやすくしています。",
    displayCut: "Display · 500", textCut: "Text · 500", atSize: "@",
    bucleLabel: "ループ", bucleTitle: "公開でつくる、一つずつのバージョン。",
    bucleBody: "バージョンごとに何かが描き直されます。前のビルドは金色で、現在のビルドの下に表示されます。",
    overlay: "重ねる", wipe: "スライド", compare: "比較", points: "点", pointsLegend: "四角はノード、丸はハンドル。数字はポイント数です。", editSample: "サンプル",
    entries: {
      xyz: { title: "x・y・z に専用のマスター。", body: "小文字26字すべてが三次曲線のマスターから生まれます。Bold の x・y・z はこう変わりました。" },
      kvw: { title: "k・v・w を描き直し。", body: "Bold k の角を整え、アクセントが文字に触れないよう k のアンカーを上げました。" },
      ijl: { title: "i・j・l がマスターに。", body: "4ウェイトすべてで正確な三次曲線と丸い端点。" },
      ft: { title: "アクセントが f と t にぶつからない。", body: "上部アンカーを上げ、f・t と記号の衝突 63 件を解消しました。" },
      display: { title: "Display が筆致を見つける。", body: "ファミリー全体の起点となる、見出し用カットの第2版。" },
    },
    legendTitle: "各文字の状態",
    master: "三次曲線マスター", derived: "Display から派生", pending: "次は大文字のマスター。",
    followLabel: "制作中", followTitle: "ループを追いかけよう。",
    followBody: "Crafter Sans はまだ制作中で、ダウンロードは公開していません。新しいバージョンはまずここに届きます。",
    github: "GitHub の Crafter Station", journal: "Journal を読む",
    ticker: ["公開でつくる", "Lima", "Bogotá", "Madrid", "1,000+ builders", "Craft. Ship. Repeat."],
  },
}
