import type { Locale } from "@/lib/i18n"

const en = {
  eyebrow: "A typeface in the making",
  intro: "The same gesture. More ways to make something. Meet the curves, characters and voices of Crafter Sans.",
  try: "Try it", family: "The family", glyphs: "Characters", uses: "In context", download: "Get the preview",
  textWeights: "text weights", characters: "characters", styles: "Display + Text",
  testerTitle: "What are you creating?",
  testerDescription: "Your words, our curves. Find their size, weight and rhythm.",
  variant: "Variant", size: "Size", spacing: "Spacing", kerning: "Kerning", reset: "Reset",
  sample: "Your text in Crafter Sans", presets: ["Craft. Ship. Repeat.", "Open source", "Accents", "Português"],
  familyTitle: "One voice. A wider range.",
  familyDescription: "Four text weights, with more presence at 16 and 18 px. Bucle Display keeps its original gesture.",
  reading: "A community turning curiosity into projects. What are you creating?",
  glyphTitle: "Get to know every curve.",
  glyphDescription: "Choose a character and look closer. These are the actual outlines of the selected font.",
  outline: "Outline", allGlyphs: "Explore all 233 characters", space: "Space",
  width: "Advance", xHeight: "x-height", capHeight: "Cap height", units: "font units",
  loading: "Loading the drawing…", unavailable: "The drawing could not load.", retry: "Try again",
  evolution: "The evolution of Bucle Display", comparison: "Comparison text", before: "Before", after: "Now",
  usesTitle: "Made to make things.",
  usesDescription: "A few places where our letters feel at home.",
  station: "Curious people. Shared ideas.", open: "Open code.", openSub: "Open possibilities.",
  coffee: "Coffee, code & community.", contextNote: "Typeface compositions, not event announcements.",
  downloadTitle: "Keep experimenting.",
  downloadDescription: "Choose a cut and a format. OTF and TTF for desktop; WOFF2 for the web.",
  format: "Format", status: "Development preview. Further optical refinement and hinting remain. No italics or variable axes yet.",
  notes: "Version and usage notes",
}

export type FontCopy = { [K in keyof typeof en]: typeof en[K] }

export const fontCopy: Record<Locale, FontCopy> = {
  en,
  es: {
    eyebrow: "Una tipografía en construcción",
    intro: "El mismo gesto. Más formas de hacer cosas. Conoce las curvas, los caracteres y las voces de Crafter Sans.",
    try: "Probar", family: "La familia", glyphs: "Caracteres", uses: "En contexto", download: "Descargar preview",
    textWeights: "pesos de texto", characters: "caracteres", styles: "Display + Text",
    testerTitle: "¿Qué estás creando?", testerDescription: "Tus palabras, nuestras curvas. Encuentra su tamaño, su peso y su ritmo.",
    variant: "Variante", size: "Tamaño", spacing: "Espaciado", kerning: "Kerning", reset: "Restablecer",
    sample: "Tu texto en Crafter Sans", presets: ["Craft. Ship. Repeat.", "Código abierto", "Acentos", "Português"],
    familyTitle: "Una voz. Más posibilidades.",
    familyDescription: "Cuatro pesos de texto, con más presencia a 16 y 18 px. Bucle Display conserva su gesto original.",
    reading: "Una comunidad para convertir la curiosidad en proyectos. ¿Qué estás creando?",
    glyphTitle: "Conoce cada curva.", glyphDescription: "Elige un carácter y míralo de cerca. Estos son los contornos reales de la fuente seleccionada.",
    outline: "Contorno", allGlyphs: "Explorar los 233 caracteres", space: "Espacio",
    width: "Avance", xHeight: "Altura de x", capHeight: "Altura de mayúsculas", units: "unidades de fuente",
    loading: "Cargando el dibujo…", unavailable: "No se pudo cargar el dibujo.", retry: "Reintentar",
    evolution: "La evolución de Bucle Display", comparison: "Texto de comparación", before: "Antes", after: "Ahora",
    usesTitle: "Una fuente para hacer cosas.", usesDescription: "Algunos lugares donde nuestras letras se sienten en casa.",
    station: "Gente curiosa. Ideas compartidas.", open: "Código abierto.", openSub: "Posibilidades abiertas.",
    coffee: "Café, código y comunidad.", contextNote: "Composiciones tipográficas, no anuncios de eventos.",
    downloadTitle: "Sigue experimentando.", downloadDescription: "Elige un peso y un formato. OTF y TTF para escritorio; WOFF2 para la web.",
    format: "Formato", status: "Preview en desarrollo. Quedan refinamiento óptico e hinting. Todavía no incluye cursivas ni ejes variables.",
    notes: "Notas de versión y uso",
  },
  pt: {
    eyebrow: "Uma tipografia em construção",
    intro: "O mesmo gesto. Mais formas de criar. Conheça as curvas, os caracteres e as vozes de Crafter Sans.",
    try: "Experimentar", family: "A família", glyphs: "Caracteres", uses: "Em contexto", download: "Baixar preview",
    textWeights: "pesos de texto", characters: "caracteres", styles: "Display + Text",
    testerTitle: "O que você está criando?", testerDescription: "Suas palavras, nossas curvas. Encontre seu tamanho, peso e ritmo.",
    variant: "Variante", size: "Tamanho", spacing: "Espaçamento", kerning: "Kerning", reset: "Redefinir",
    sample: "Seu texto em Crafter Sans", presets: ["Craft. Ship. Repeat.", "Código aberto", "Acentos", "Português"],
    familyTitle: "Uma voz. Mais possibilidades.",
    familyDescription: "Quatro pesos de texto, com mais presença em 16 e 18 px. Bucle Display mantém seu gesto original.",
    reading: "Uma comunidade para transformar a curiosidade em projetos. O que você está criando?",
    glyphTitle: "Conheça cada curva.", glyphDescription: "Escolha um caractere e veja de perto. Estes são os contornos reais da fonte selecionada.",
    outline: "Contorno", allGlyphs: "Explorar os 233 caracteres", space: "Espaço",
    width: "Avanço", xHeight: "Altura de x", capHeight: "Altura das maiúsculas", units: "unidades da fonte",
    loading: "Carregando o desenho…", unavailable: "Não foi possível carregar o desenho.", retry: "Tentar novamente",
    evolution: "A evolução de Bucle Display", comparison: "Texto de comparação", before: "Antes", after: "Agora",
    usesTitle: "Uma fonte para criar.", usesDescription: "Alguns lugares onde nossas letras se sentem em casa.",
    station: "Gente curiosa. Ideias compartilhadas.", open: "Código aberto.", openSub: "Possibilidades abertas.",
    coffee: "Café, código e comunidade.", contextNote: "Composições tipográficas, não anúncios de eventos.",
    downloadTitle: "Continue experimentando.", downloadDescription: "Escolha um peso e um formato. OTF e TTF para desktop; WOFF2 para a web.",
    format: "Formato", status: "Preview em desenvolvimento. Ainda faltam refinamento óptico e hinting. Sem itálicos ou eixos variáveis.",
    notes: "Notas de versão e uso",
  },
  zh: {
    eyebrow: "一款正在成长的字体",
    intro: "同样的笔触，更多创造的方式。探索 Crafter Sans 的曲线、字符与不同字重。",
    try: "试用", family: "字体家族", glyphs: "字符", uses: "应用展示", download: "下载预览",
    textWeights: "种正文字重", characters: "个字符", styles: "Display + Text",
    testerTitle: "你正在创造什么？", testerDescription: "用你的文字，探索我们的曲线、大小、字重与节奏。",
    variant: "样式", size: "字号", spacing: "字距", kerning: "字偶距", reset: "重置",
    sample: "输入文字试用 Crafter Sans", presets: ["Craft. Ship. Repeat.", "开源", "重音符号", "Português"],
    familyTitle: "同一种声音，更多表达。",
    familyDescription: "四种正文字重，让 16 和 18 px 的文字更清晰。Bucle Display 保留原有笔触。",
    reading: "A community turning curiosity into projects. What are you creating?",
    glyphTitle: "认识每一条曲线。", glyphDescription: "选择一个字符，近距离查看当前字体的真实轮廓。",
    outline: "轮廓", allGlyphs: "探索全部 233 个字符", space: "空格",
    width: "前进宽度", xHeight: "x 高度", capHeight: "大写高度", units: "字体单位",
    loading: "正在加载字形…", unavailable: "无法加载字形。", retry: "重试",
    evolution: "Bucle Display 的演变", comparison: "对比文字", before: "之前", after: "现在",
    usesTitle: "为创造而生。", usesDescription: "让字母自然融入我们熟悉的场景。",
    station: "好奇的人，共享的想法。", open: "开放代码。", openSub: "开放可能。",
    coffee: "咖啡、代码与社区。", contextNote: "字体应用示例，并非活动公告。",
    downloadTitle: "继续探索。", downloadDescription: "选择字重与格式。OTF 和 TTF 用于桌面，WOFF2 用于网页。",
    format: "格式", status: "开发预览版，仍需视觉细化与 hinting。暂不包含斜体或可变字体轴。",
    notes: "版本与使用说明",
  },
  ja: {
    eyebrow: "育ち続ける書体",
    intro: "同じ筆致から、もっと多くの表現へ。Crafter Sans の曲線、文字、ウェイトを探索しよう。",
    try: "試す", family: "ファミリー", glyphs: "文字", uses: "使用例", download: "プレビューを入手",
    textWeights: "種類の本文ウェイト", characters: "文字", styles: "Display + Text",
    testerTitle: "何をつくっていますか？", testerDescription: "あなたの言葉で、サイズ、太さ、文字のリズムを試してみよう。",
    variant: "スタイル", size: "サイズ", spacing: "字間", kerning: "カーニング", reset: "リセット",
    sample: "Crafter Sans で文字を試す", presets: ["Craft. Ship. Repeat.", "オープンソース", "アクセント", "Português"],
    familyTitle: "ひとつの声、広がる表現。",
    familyDescription: "16・18 px で読みやすさを高めた4つの本文ウェイト。Bucle Display は元の筆致を保ちます。",
    reading: "A community turning curiosity into projects. What are you creating?",
    glyphTitle: "曲線をもっと近くで。", glyphDescription: "文字を選ぶと、選択中のフォントの実際の輪郭を確認できます。",
    outline: "輪郭", allGlyphs: "全233文字を見る", space: "スペース",
    width: "送り幅", xHeight: "xハイト", capHeight: "大文字の高さ", units: "フォント単位",
    loading: "字形を読み込み中…", unavailable: "字形を読み込めませんでした。", retry: "再試行",
    evolution: "Bucle Display の変遷", comparison: "比較用テキスト", before: "以前", after: "現在",
    usesTitle: "つくるための書体。", usesDescription: "私たちの文字が自然になじむ、いくつかの場所。",
    station: "好奇心を持つ人々。分かち合うアイデア。", open: "開かれたコード。", openSub: "広がる可能性。",
    coffee: "コーヒー、コード、コミュニティ。", contextNote: "書体の使用例であり、イベントの告知ではありません。",
    downloadTitle: "もっと試してみよう。", downloadDescription: "ウェイトと形式を選択。OTF・TTF はデスクトップ用、WOFF2 はウェブ用です。",
    format: "形式", status: "開発中のプレビューです。視覚的な調整とヒンティングが必要です。イタリックや可変軸はまだありません。",
    notes: "バージョンと使用上の注意",
  },
}
