import type { Locale } from "@/lib/i18n"

type HomeCopy = {
  work: string; workBody: string; allProjects: string; catalog: string
  events: string; eventsBody: string; calendar: string; sponsor: string
  brew: string; ship: string; people: string; peopleTitle: string
  peopleBody: string; peopleNote: string; meetTeam: string; join: string
  family: string; familyTitle: string; familyBody: string
  journal: string; journalTitle: string; allPosts: string; explore: string
  community: string; ships: string; docs: string; workWithUs: string
}

export const homeCopy: Record<Locale, HomeCopy> = {
  es: {
    work: "Del «¿y si…?» al «ya está».",
    workBody: "Herramientas útiles, pequeños experimentos y algunas ideas que se nos fueron de las manos. Todo empieza haciendo.",
    allProjects: "Todos los proyectos", catalog: "Selección del taller",
    events: "Pantallas abajo.\nIdeas arriba.",
    eventsBody: "A veces, el siguiente paso de un proyecto es conocer a alguien.",
    calendar: "Ver próximos encuentros", sponsor: "Organiza algo con nosotros",
    brew: "Café, código\ny una buena charla.", ship: "Una idea.\nUna tripulación.\nA construir.",
    people: "La gente detrás", peopleTitle: "Aquí siempre\ncabe alguien más.",
    peopleBody: "Ven con una idea, una pregunta o algo a medio hacer. Nos gusta compartir lo que aprendemos y conocer a quienes están construyendo.",
    peopleNote: "Las conversaciones también son parte del proceso.",
    meetTeam: "Conoce al equipo y sus calendarios", join: "Entra a la comunidad",
    family: "El universo Crafter", familyTitle: "Una misma chispa.\nCuatro direcciones.",
    familyBody: "Construir, investigar, jugar, experimentar. Cada espacio tiene su carácter. La curiosidad es compartida.",
    journal: "Notas del taller", journalTitle: "Aprender.\nCompartir.\nVolver a hacer.",
    allPosts: "Leer el blog", explore: "Sigue tu curiosidad",
    community: "Comunidad", ships: "Lo que estamos lanzando", docs: "Documentación", workWithUs: "Trabaja con nosotros",
  },
  en: {
    work: "From “what if” to “it’s live”.",
    workBody: "Useful tools, small experiments, and a few ideas that got out of hand. It all starts with making.",
    allProjects: "All projects", catalog: "From the workbench",
    events: "Screens down.\nIdeas up.",
    eventsBody: "Sometimes, the next step for a project is meeting someone.",
    calendar: "See upcoming gatherings", sponsor: "Host something with us",
    brew: "Coffee, code,\nand a good conversation.", ship: "One idea.\nOne crew.\nLet’s build.",
    people: "The people behind it", peopleTitle: "There’s always\nroom for one more.",
    peopleBody: "Bring an idea, a question, or something half finished. We like sharing what we learn and meeting people who are making things.",
    peopleNote: "Conversations are part of the process, too.",
    meetTeam: "Meet the team and find their calendars", join: "Join the community",
    family: "The Crafter universe", familyTitle: "One shared spark.\nFour directions.",
    familyBody: "Build, research, play, experiment. Every space has its own character. Curiosity connects us.",
    journal: "Workbench notes", journalTitle: "Learn.\nShare.\nMake again.",
    allPosts: "Read the blog", explore: "Follow your curiosity",
    community: "Community", ships: "What we’re shipping", docs: "Documentation", workWithUs: "Work with us",
  },
  pt: {
    work: "Do «e se…?» ao «está no ar».",
    workBody: "Ferramentas úteis, pequenos experimentos e algumas ideias que foram além do esperado. Tudo começa fazendo.",
    allProjects: "Todos os projetos", catalog: "Seleção da oficina",
    events: "Telas de lado.\nIdeias em alta.",
    eventsBody: "Às vezes, o próximo passo de um projeto é conhecer alguém.",
    calendar: "Ver próximos encontros", sponsor: "Organize algo com a gente",
    brew: "Café, código\ne uma boa conversa.", ship: "Uma ideia.\nUma equipe.\nVamos construir.",
    people: "Quem faz acontecer", peopleTitle: "Sempre cabe\nmais alguém.",
    peopleBody: "Traga uma ideia, uma pergunta ou algo pela metade. Gostamos de compartilhar o que aprendemos e conhecer quem está criando.",
    peopleNote: "As conversas também fazem parte do processo.",
    meetTeam: "Conheça a equipe e seus calendários", join: "Entre na comunidade",
    family: "O universo Crafter", familyTitle: "Uma mesma faísca.\nQuatro direções.",
    familyBody: "Construir, pesquisar, jogar, experimentar. Cada espaço tem sua personalidade. A curiosidade é compartilhada.",
    journal: "Notas da oficina", journalTitle: "Aprender.\nCompartilhar.\nCriar de novo.",
    allPosts: "Ler o blog", explore: "Siga sua curiosidade",
    community: "Comunidade", ships: "O que estamos lançando", docs: "Documentação", workWithUs: "Trabalhe conosco",
  },
  zh: {
    work: "从「如果」到「上线」。",
    workBody: "实用工具、小小实验，还有一些越做越大的点子。一切从动手开始。",
    allProjects: "所有项目", catalog: "工作台精选",
    events: "放下屏幕。\n点亮想法。",
    eventsBody: "有时，项目的下一步，是遇见一个人。",
    calendar: "查看即将举行的活动", sponsor: "一起举办活动",
    brew: "咖啡、代码，\n聊点有趣的。", ship: "一个想法。\n一支团队。\n开始创造。",
    people: "背后的伙伴", peopleTitle: "这里总有\n你的位置。",
    peopleBody: "带上一个想法、一个问题，或一个未完成的作品。我们乐于分享所学，也想认识正在创造的人。",
    peopleNote: "交流，也是创造的一部分。",
    meetTeam: "认识团队，查看预约日历", join: "加入社区",
    family: "Crafter 宇宙", familyTitle: "同一份热情。\n四种方向。",
    familyBody: "构建、研究、游戏、实验。每个空间都有个性，共同的好奇心将我们连接。",
    journal: "工作台笔记", journalTitle: "学习。\n分享。\n再次创造。",
    allPosts: "阅读博客", explore: "跟随你的好奇心",
    community: "社区", ships: "正在发布的作品", docs: "文档", workWithUs: "与我们合作",
  },
  ja: {
    work: "「もしも」から「できた」へ。",
    workBody: "便利なツール、小さな実験、思いがけず広がったアイデア。すべては、つくることから。",
    allProjects: "すべてのプロジェクト", catalog: "ワークベンチから",
    events: "画面を閉じて。\nアイデアを広げて。",
    eventsBody: "プロジェクトの次の一歩は、誰かとの出会いかもしれません。",
    calendar: "今後のイベントを見る", sponsor: "一緒にイベントを開こう",
    brew: "コーヒーとコード、\nそしていい会話。", ship: "ひとつのアイデア。\nひとつのチーム。\nさあ、つくろう。",
    people: "つくる仲間たち", peopleTitle: "あなたの居場所も、\nここにある。",
    peopleBody: "アイデアでも、質問でも、つくりかけのものでも。学んだことを分かち合い、つくる人たちと出会いたい。",
    peopleNote: "会話も、つくるプロセスの一部。",
    meetTeam: "チームと予約カレンダーを見る", join: "コミュニティに参加",
    family: "Crafter の世界", familyTitle: "同じひらめき。\n四つの方向。",
    familyBody: "構築、研究、遊び、実験。それぞれの個性を、共通の好奇心がつなぎます。",
    journal: "ワークベンチノート", journalTitle: "学ぶ。\n共有する。\nまたつくる。",
    allPosts: "ブログを読む", explore: "好奇心のままに",
    community: "コミュニティ", ships: "リリースしたもの", docs: "ドキュメント", workWithUs: "一緒に働く",
  },
}
