import type { Locale } from "@/lib/i18n"

const en = {
  agenda: "Agenda", editions: "Editions", edition: "Edition {number}", announcements: "Announcements",
  tagline: "Coffee, code and community",
  description: "A coffee with the dev community. Bring your side project, share what you're building and meet the people behind it.",
  editionDescription: "Bring your side project, something to show or a question for the table, or simply come to meet the community.",
  upcoming: "Upcoming", live: "Happening now", past: "Finished", started: "Already started", unannounced: "Date to be announced",
  seats: "{count} spots", posterAlt: "Hot Reload #{number} poster · {date} · {city}",
  register: "Register on Luma", viewEvent: "View event on Luma", calendar: "View the calendar on Luma", linkedin: "View on LinkedIn",
  menu: "Choose your order", viewOrder: "View my order", order: "Order",
  menuDescription: "Choose your drink and food for Hot Reload at {venue}.",
  menuIntro: "One drink and one food item at {venue}, up to {amount} per person. Crafter Station is treating.",
  deadline: "You can place or change your order until {date}.",
  ordersOpen: "Orders open", ordersClosed: "Orders closed", ordersPending: "Orders not open yet",
  closedBody: "The order deadline has passed. Saved orders remain available here.",
  pendingBody: "The date and order deadline will be announced here.",
  signInTitle: "Sign in to order", signInBody: "Use the email you registered with on Luma so we can confirm your spot.", signIn: "Sign in",
  pendingTitle: "Your spot is not confirmed yet", pendingGuest: "Your registration with {email} is still awaiting approval. Come back once Luma confirms your spot.",
  missingTitle: "We couldn't find your email on Luma", missingGuest: "We checked {emails}, but couldn't find a registration for this event.",
  requestSpot: "Request a spot on Luma", unavailableTitle: "We couldn't check the guest list", unavailableBody: "Luma didn't respond. Please try again in a few minutes.",
  drink: "Drink", food: "Food", clear: "Clear selection", categories: "{name} categories",
  hot: "Hot", cold: "Cold", other: "Without coffee", sweet: "Sweet", savory: "Savory",
  overBy: "{amount} over the limit", remaining: "{amount} remaining", outOf: "of {amount}",
  details: "Your details", name: "Name", email: "Luma email", existing: "You already have an order. Saving again replaces it.",
  confirmedEmail: "Your spot is confirmed on Luma with this email.", total: "Total", noDrink: "No drink", noFood: "No food", submit: "Save order",
  saved: "Order saved", savedBody: "We'll have it ready for you at Hot Reload. See you there.", change: "Change order", noOrder: "You didn't save an order for this edition.",
  errorClosed: "Orders for this edition are closed.", errorUnavailable: "We couldn't save your order. Please try again.",
  errorAuth: "Sign in to send your order.", errorApproval: "Your email does not have an approved spot on Luma.",
  errorName: "Enter a name between 2 and 80 characters.", errorItems: "Choose one drink and one food item from this edition's menu.",
  errorBudget: "That combination exceeds {amount}. Please choose another.",
  linkTitle: "Used a different email on Luma?", linkBody: "Link it to your account. We'll send a code to confirm it's yours.",
  codeSent: "Enter the code sent to {email}.", code: "Verification code", verify: "Verify", sendCode: "Send code", anotherEmail: "Use another email",
  linkError: "We couldn't link that email. Check the address and try again.", verifyError: "We couldn't verify the code. Check it or request a new one.",
  emailPlaceholder: "you@example.com", admin: "Admin", eventOrders: "Event orders", orders: "Orders", viewOrders: "View orders",
  download: "Download for Excel (.csv)", databaseUnavailable: "Orders are temporarily unavailable. Please try again.",
  average: "Average", drinks: "Drinks", foods: "Food", detail: "Details", updated: "Updated", created: "Created", drinkPrice: "Drink price", foodPrice: "Food price",
  noOrders: "There are no orders for this edition yet.", emptyEditions: "New editions will be announced here.",
}

type Copy = { [K in keyof typeof en]: string }

export const hotReloadCopy: Record<Locale, Copy> = {
  en,
  es: {
    agenda: "Agenda", editions: "Ediciones", edition: "Edición {number}", announcements: "Anuncios",
    tagline: "Café, código y comunidad",
    description: "Un café con la comunidad dev. Trae tu side project, comparte lo que estás construyendo y conoce a la gente detrás.",
    editionDescription: "Trae tu side project, algo que quieras mostrar o una pregunta para la mesa, o ven a conocer a la comunidad.",
    upcoming: "Próximo", live: "En curso", past: "Finalizado", started: "Ya comenzó", unannounced: "Fecha por anunciar",
    seats: "{count} cupos", posterAlt: "Afiche de Hot Reload #{number} · {date} · {city}",
    register: "Registrarme en Luma", viewEvent: "Ver evento en Luma", calendar: "Ver la agenda en Luma", linkedin: "Ver en LinkedIn",
    menu: "Elige tu pedido", viewOrder: "Ver mi pedido", order: "Pedido",
    menuDescription: "Elige tu bebida y comida para Hot Reload en {venue}.",
    menuIntro: "Una bebida y una comida de {venue}, hasta {amount} por persona. Invita Crafter Station.",
    deadline: "Puedes hacer o cambiar tu pedido hasta el {date}.",
    ordersOpen: "Pedidos abiertos", ordersClosed: "Pedidos cerrados", ordersPending: "Pedidos aún no disponibles",
    closedBody: "Terminó el plazo para pedir. Los pedidos guardados siguen disponibles aquí.",
    pendingBody: "Aquí anunciaremos la fecha y el cierre de pedidos.",
    signInTitle: "Inicia sesión para pedir", signInBody: "Entra con el correo con el que pediste tu cupo en Luma para que podamos confirmarlo.", signIn: "Iniciar sesión",
    pendingTitle: "Tu cupo todavía no está confirmado", pendingGuest: "Tu registro con {email} sigue pendiente de aprobación. Vuelve cuando Luma confirme tu cupo.",
    missingTitle: "No encontramos tu correo en Luma", missingGuest: "Revisamos {emails}, pero no encontramos un registro para este evento.",
    requestSpot: "Solicita tu cupo en Luma", unavailableTitle: "No pudimos revisar la lista", unavailableBody: "Luma no respondió. Intenta de nuevo en unos minutos.",
    drink: "Bebida", food: "Comida", clear: "Quitar selección", categories: "Categorías de {name}",
    hot: "Calientes", cold: "Fríos", other: "Sin café", sweet: "Dulces", savory: "Salados",
    overBy: "Te pasas del tope por {amount}", remaining: "Te quedan {amount}", outOf: "de {amount}",
    details: "Tus datos", name: "Nombre", email: "Correo de Luma", existing: "Ya tienes un pedido. Si lo cambias, se reemplaza.",
    confirmedEmail: "Tu cupo está confirmado en Luma con este correo.", total: "Total", noDrink: "Sin bebida", noFood: "Sin comida", submit: "Guardar pedido",
    saved: "Pedido guardado", savedBody: "Te lo tenemos listo en el Hot Reload. Nos vemos ahí.", change: "Cambiar pedido", noOrder: "No guardaste un pedido para esta edición.",
    errorClosed: "Los pedidos de esta edición están cerrados.", errorUnavailable: "No pudimos guardar tu pedido. Intenta otra vez.",
    errorAuth: "Inicia sesión para enviar tu pedido.", errorApproval: "Tu correo no tiene un cupo aprobado en Luma.",
    errorName: "Escribe un nombre de entre 2 y 80 caracteres.", errorItems: "Elige una bebida y una comida de la carta de esta edición.",
    errorBudget: "Esa combinación pasa los {amount}. Elige otra.",
    linkTitle: "¿Usaste otro correo en Luma?", linkBody: "Vincúlalo a tu cuenta. Te mandamos un código para confirmar que es tuyo.",
    codeSent: "Escribe el código que te mandamos a {email}.", code: "Código de verificación", verify: "Verificar", sendCode: "Enviar código", anotherEmail: "Usar otro correo",
    linkError: "No pudimos vincular ese correo. Revisa la dirección e inténtalo de nuevo.", verifyError: "No pudimos verificar el código. Revísalo o solicita uno nuevo.",
    emailPlaceholder: "tu@correo.com", admin: "Admin", eventOrders: "Pedidos de eventos", orders: "Pedidos", viewOrders: "Ver pedidos",
    download: "Descargar para Excel (.csv)", databaseUnavailable: "Los pedidos no están disponibles por un momento. Intenta de nuevo.",
    average: "Promedio", drinks: "Bebidas", foods: "Comidas", detail: "Detalle", updated: "Actualizado", created: "Creado", drinkPrice: "Precio de bebida", foodPrice: "Precio de comida",
    noOrders: "Todavía no hay pedidos para esta edición.", emptyEditions: "Aquí anunciaremos las próximas ediciones.",
  },
  pt: {
    agenda: "Agenda", editions: "Edições", edition: "Edição {number}", announcements: "Anúncios",
    tagline: "Café, código e comunidade",
    description: "Um café com a comunidade dev. Traga seu side project, compartilhe o que está construindo e conheça quem está por trás.",
    editionDescription: "Traga seu side project, algo para mostrar ou uma pergunta para a mesa, ou venha conhecer a comunidade.",
    upcoming: "Em breve", live: "Em andamento", past: "Encerrado", started: "Já começou", unannounced: "Data a anunciar",
    seats: "{count} vagas", posterAlt: "Cartaz do Hot Reload #{number} · {date} · {city}",
    register: "Inscrever-se no Luma", viewEvent: "Ver evento no Luma", calendar: "Ver a agenda no Luma", linkedin: "Ver no LinkedIn",
    menu: "Escolha seu pedido", viewOrder: "Ver meu pedido", order: "Pedido",
    menuDescription: "Escolha sua bebida e comida para o Hot Reload no {venue}.",
    menuIntro: "Uma bebida e uma comida do {venue}, até {amount} por pessoa. A Crafter Station convida.",
    deadline: "Você pode fazer ou alterar seu pedido até {date}.",
    ordersOpen: "Pedidos abertos", ordersClosed: "Pedidos encerrados", ordersPending: "Pedidos ainda indisponíveis",
    closedBody: "O prazo para pedir terminou. Os pedidos salvos continuam disponíveis aqui.",
    pendingBody: "A data e o prazo dos pedidos serão anunciados aqui.",
    signInTitle: "Entre para fazer seu pedido", signInBody: "Use o e-mail da sua inscrição no Luma para confirmarmos sua vaga.", signIn: "Entrar",
    pendingTitle: "Sua vaga ainda não foi confirmada", pendingGuest: "Sua inscrição com {email} aguarda aprovação. Volte quando o Luma confirmar sua vaga.",
    missingTitle: "Não encontramos seu e-mail no Luma", missingGuest: "Verificamos {emails}, mas não encontramos uma inscrição para este evento.",
    requestSpot: "Solicite sua vaga no Luma", unavailableTitle: "Não foi possível consultar a lista", unavailableBody: "O Luma não respondeu. Tente novamente em alguns minutos.",
    drink: "Bebida", food: "Comida", clear: "Limpar seleção", categories: "Categorias de {name}",
    hot: "Quentes", cold: "Geladas", other: "Sem café", sweet: "Doces", savory: "Salgados",
    overBy: "{amount} acima do limite", remaining: "Restam {amount}", outOf: "de {amount}",
    details: "Seus dados", name: "Nome", email: "E-mail do Luma", existing: "Você já tem um pedido. Salvar novamente o substitui.",
    confirmedEmail: "Sua vaga está confirmada no Luma com este e-mail.", total: "Total", noDrink: "Sem bebida", noFood: "Sem comida", submit: "Salvar pedido",
    saved: "Pedido salvo", savedBody: "Estará pronto para você no Hot Reload. Até lá.", change: "Alterar pedido", noOrder: "Você não salvou um pedido para esta edição.",
    errorClosed: "Os pedidos desta edição estão encerrados.", errorUnavailable: "Não foi possível salvar seu pedido. Tente novamente.",
    errorAuth: "Entre para enviar seu pedido.", errorApproval: "Seu e-mail não tem uma vaga aprovada no Luma.",
    errorName: "Digite um nome entre 2 e 80 caracteres.", errorItems: "Escolha uma bebida e uma comida do cardápio desta edição.",
    errorBudget: "Essa combinação ultrapassa {amount}. Escolha outra.",
    linkTitle: "Usou outro e-mail no Luma?", linkBody: "Vincule-o à sua conta. Enviaremos um código para confirmar que é seu.",
    codeSent: "Digite o código enviado para {email}.", code: "Código de verificação", verify: "Verificar", sendCode: "Enviar código", anotherEmail: "Usar outro e-mail",
    linkError: "Não foi possível vincular esse e-mail. Confira o endereço e tente novamente.", verifyError: "Não foi possível verificar o código. Confira-o ou solicite outro.",
    emailPlaceholder: "voce@exemplo.com", admin: "Admin", eventOrders: "Pedidos de eventos", orders: "Pedidos", viewOrders: "Ver pedidos",
    download: "Baixar para Excel (.csv)", databaseUnavailable: "Os pedidos estão temporariamente indisponíveis. Tente novamente.",
    average: "Média", drinks: "Bebidas", foods: "Comidas", detail: "Detalhes", updated: "Atualizado", created: "Criado", drinkPrice: "Preço da bebida", foodPrice: "Preço da comida",
    noOrders: "Ainda não há pedidos para esta edição.", emptyEditions: "As próximas edições serão anunciadas aqui.",
  },
  zh: {
    agenda: "活动日历", editions: "各期活动", edition: "第 {number} 期", announcements: "公告",
    tagline: "咖啡、代码与社区",
    description: "和开发者社区喝杯咖啡。带上你的个人项目，分享正在构建的作品，认识背后的伙伴。",
    editionDescription: "带上你的个人项目、想展示的作品或想交流的问题，也欢迎来认识社区伙伴。",
    upcoming: "即将举行", live: "进行中", past: "已结束", started: "已开始", unannounced: "日期待公布",
    seats: "{count} 个名额", posterAlt: "Hot Reload 第 {number} 期海报 · {date} · {city}",
    register: "前往 Luma 报名", viewEvent: "在 Luma 查看活动", calendar: "在 Luma 查看日历", linkedin: "在 LinkedIn 查看",
    menu: "选择你的餐点", viewOrder: "查看我的订单", order: "订单",
    menuDescription: "为在 {venue} 举办的 Hot Reload 选择饮品和餐点。",
    menuIntro: "在 {venue} 选择一份饮品和一份餐点，每人预算 {amount}。由 Crafter Station 招待。",
    deadline: "可在 {date} 之前下单或修改订单。",
    ordersOpen: "可以点单", ordersClosed: "点单已截止", ordersPending: "点单尚未开放",
    closedBody: "点单时间已截止。已保存的订单仍可在这里查看。",
    pendingBody: "活动日期和点单截止时间将在这里公布。",
    signInTitle: "登录后点单", signInBody: "请使用在 Luma 报名时的邮箱，以便确认你的名额。", signIn: "登录",
    pendingTitle: "你的名额尚未确认", pendingGuest: "使用 {email} 提交的报名仍在等待批准。Luma 确认名额后，请再回来点单。",
    missingTitle: "在 Luma 未找到你的邮箱", missingGuest: "已检查 {emails}，但没有找到本次活动的报名记录。",
    requestSpot: "在 Luma 申请名额", unavailableTitle: "暂时无法查看报名名单", unavailableBody: "Luma 未响应，请过几分钟重试。",
    drink: "饮品", food: "餐点", clear: "取消选择", categories: "{name}分类",
    hot: "热饮", cold: "冷饮", other: "非咖啡饮品", sweet: "甜点", savory: "咸点",
    overBy: "超出预算 {amount}", remaining: "剩余 {amount}", outOf: "预算 {amount}",
    details: "你的信息", name: "姓名", email: "Luma 邮箱", existing: "你已有订单。再次保存将替换原订单。",
    confirmedEmail: "该邮箱在 Luma 的活动名额已确认。", total: "总计", noDrink: "未选饮品", noFood: "未选餐点", submit: "保存订单",
    saved: "订单已保存", savedBody: "我们会在 Hot Reload 为你准备好。到时见。", change: "修改订单", noOrder: "你没有为本期活动保存订单。",
    errorClosed: "本期活动点单已截止。", errorUnavailable: "无法保存订单，请重试。",
    errorAuth: "请登录后提交订单。", errorApproval: "该邮箱在 Luma 没有已批准的活动名额。",
    errorName: "请输入 2 至 80 个字符的姓名。", errorItems: "请从本期菜单中选择一份饮品和一份餐点。",
    errorBudget: "此组合超过 {amount}，请选择其他组合。",
    linkTitle: "在 Luma 使用了其他邮箱？", linkBody: "将它关联到你的账号。我们会发送验证码确认邮箱归属。",
    codeSent: "请输入发送到 {email} 的验证码。", code: "验证码", verify: "验证", sendCode: "发送验证码", anotherEmail: "使用其他邮箱",
    linkError: "无法关联该邮箱，请检查地址后重试。", verifyError: "验证码验证失败，请检查或重新获取。",
    emailPlaceholder: "you@example.com", admin: "管理", eventOrders: "活动订单", orders: "订单", viewOrders: "查看订单",
    download: "下载 Excel 可读文件（.csv）", databaseUnavailable: "订单暂时不可用，请重试。",
    average: "平均金额", drinks: "饮品", foods: "餐点", detail: "明细", updated: "更新时间", created: "创建时间", drinkPrice: "饮品价格", foodPrice: "餐点价格",
    noOrders: "本期活动还没有订单。", emptyEditions: "新一期活动将在这里公布。",
  },
  ja: {
    agenda: "イベント予定", editions: "開催一覧", edition: "第 {number} 回", announcements: "お知らせ",
    tagline: "コーヒー、コード、コミュニティ",
    description: "開発者コミュニティとコーヒーを。個人プロジェクトを持ち寄り、つくっているものを共有して、仲間と出会おう。",
    editionDescription: "個人プロジェクトや見せたいもの、話し合いたい質問を持ち寄ろう。仲間に会いに来るだけでも歓迎です。",
    upcoming: "開催予定", live: "開催中", past: "終了", started: "開始済み", unannounced: "日程は後日発表",
    seats: "定員 {count} 名", posterAlt: "Hot Reload 第 {number} 回のポスター · {date} · {city}",
    register: "Luma で参加登録", viewEvent: "Luma でイベントを見る", calendar: "Luma で予定を見る", linkedin: "LinkedIn で見る",
    menu: "注文を選ぶ", viewOrder: "自分の注文を見る", order: "注文",
    menuDescription: "{venue} で開催する Hot Reload のドリンクとフードを選ぼう。",
    menuIntro: "{venue} のドリンクとフードを一品ずつ、一人 {amount} まで。Crafter Station がごちそうします。",
    deadline: "{date} まで注文・変更できます。",
    ordersOpen: "注文受付中", ordersClosed: "注文受付終了", ordersPending: "注文受付前",
    closedBody: "注文の締め切りを過ぎました。保存済みの注文は引き続きここで確認できます。",
    pendingBody: "日程と注文の締め切りはこちらでお知らせします。",
    signInTitle: "ログインして注文", signInBody: "参加確認のため、Luma に登録したメールアドレスでログインしてください。", signIn: "ログイン",
    pendingTitle: "参加はまだ確定していません", pendingGuest: "{email} での登録は承認待ちです。Luma で参加が確定したら、もう一度お越しください。",
    missingTitle: "Luma にメールアドレスが見つかりません", missingGuest: "{emails} を確認しましたが、このイベントの登録が見つかりませんでした。",
    requestSpot: "Luma で参加を申し込む", unavailableTitle: "参加者リストを確認できませんでした", unavailableBody: "Luma から応答がありません。数分後にもう一度お試しください。",
    drink: "ドリンク", food: "フード", clear: "選択を解除", categories: "{name}のカテゴリー",
    hot: "ホット", cold: "コールド", other: "コーヒー以外", sweet: "スイーツ", savory: "軽食",
    overBy: "上限を {amount} 超過", remaining: "残り {amount}", outOf: "上限 {amount}",
    details: "お客様情報", name: "お名前", email: "Luma のメールアドレス", existing: "保存済みの注文があります。再度保存すると上書きされます。",
    confirmedEmail: "このメールアドレスで Luma の参加が確定しています。", total: "合計", noDrink: "ドリンク未選択", noFood: "フード未選択", submit: "注文を保存",
    saved: "注文を保存しました", savedBody: "Hot Reload でご用意してお待ちしています。", change: "注文を変更", noOrder: "この回の注文は保存されていません。",
    errorClosed: "この回の注文受付は終了しました。", errorUnavailable: "注文を保存できませんでした。もう一度お試しください。",
    errorAuth: "ログインして注文を送信してください。", errorApproval: "このメールアドレスの参加は Luma で承認されていません。",
    errorName: "お名前は 2〜80 文字で入力してください。", errorItems: "この回のメニューからドリンクとフードを一品ずつ選んでください。",
    errorBudget: "この組み合わせは {amount} を超えています。別のものをお選びください。",
    linkTitle: "Luma で別のメールアドレスを使いましたか？", linkBody: "アカウントに追加しましょう。ご本人のアドレスであることを確認するコードをお送りします。",
    codeSent: "{email} に送信したコードを入力してください。", code: "確認コード", verify: "確認", sendCode: "コードを送信", anotherEmail: "別のメールアドレスを使う",
    linkError: "メールアドレスを追加できませんでした。アドレスを確認して再度お試しください。", verifyError: "コードを確認できませんでした。入力を確認するか、新しいコードを取得してください。",
    emailPlaceholder: "you@example.com", admin: "管理", eventOrders: "イベントの注文", orders: "注文", viewOrders: "注文を見る",
    download: "Excel 用にダウンロード（.csv）", databaseUnavailable: "注文を一時的に表示できません。再度お試しください。",
    average: "平均", drinks: "ドリンク", foods: "フード", detail: "明細", updated: "更新日時", created: "作成日時", drinkPrice: "ドリンクの価格", foodPrice: "フードの価格",
    noOrders: "この回の注文はまだありません。", emptyEditions: "次回の開催はこちらでお知らせします。",
  },
}

export function hotReloadText(template: string, values: Record<string, string | number>) {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => String(values[key] ?? match))
}

export function eventMoney(amount: number, locale: Locale, currency = "PEN") {
  return new Intl.NumberFormat(locale === "es" ? "es-PE" : locale, { style: "currency", currency, currencyDisplay: "narrowSymbol", maximumFractionDigits: 2, minimumFractionDigits: 0 }).format(amount)
}
