export const navCopy = {
  en: {
    community: "Community",
    ships: "Ships",
    bounties: "Bounties",
    crafters: "Crafters",
    events: "Calendar",
    hackathon: "Hackathons",
    blog: "Journal",
    oss: "Open source",
    universe: "Universe",
    research: "Research",
    impact: "Impact",
    team: "Team",
    ossMetrics: "OSS metrics",
    timeline: "Project activity",
    workWithUs: "Collaborate",
    brandPartnerships: "Events & partnerships",
    contact: "Contact",
    communityCta: "Join the community",
    language: "Language",
    theme: "Theme",
    openMenu: "Open menu",
  },
  es: {
    community: "Comunidad",
    ships: "Ships",
    bounties: "Bounties",
    crafters: "Crafters",
    events: "Agenda",
    hackathon: "Hackathons",
    blog: "Journal",
    oss: "Código abierto",
    universe: "Universo",
    research: "Investigación",
    impact: "Impacto",
    team: "Equipo",
    ossMetrics: "Métricas OSS",
    timeline: "Actividad de proyectos",
    workWithUs: "Colaborar",
    brandPartnerships: "Eventos y alianzas",
    contact: "Contacto",
    communityCta: "Únete a la comunidad",
    language: "Idioma",
    theme: "Tema",
    openMenu: "Abrir menú",
  },
  pt: {
    community: "Comunidade",
    ships: "Ships",
    bounties: "Bounties",
    crafters: "Crafters",
    events: "Agenda",
    hackathon: "Hackathons",
    blog: "Journal",
    oss: "Codigo aberto",
    universe: "Universo",
    research: "Pesquisa",
    impact: "Impacto",
    team: "Equipe",
    ossMetrics: "Metricas OSS",
    timeline: "Atividade dos projetos",
    workWithUs: "Colaborar",
    brandPartnerships: "Eventos e parcerias",
    contact: "Contato",
    communityCta: "Entre na comunidade",
    language: "Idioma",
    theme: "Tema",
    openMenu: "Abrir menu",
  },
  zh: {
    community: "社区",
    ships: "社区作品",
    bounties: "Bounties 挑战",
    crafters: "成员",
    events: "活动日历",
    hackathon: "黑客松",
    blog: "Journal",
    oss: "开源",
    universe: "Crafter 宇宙",
    research: "研究",
    impact: "影响力",
    team: "团队",
    ossMetrics: "开源指标",
    timeline: "项目动态",
    workWithUs: "一起合作",
    brandPartnerships: "活动与合作",
    contact: "联系我们",
    communityCta: "加入社区",
    language: "语言",
    theme: "主题",
    openMenu: "打开菜单",
  },
  ja: {
    community: "コミュニティ",
    ships: "コミュニティ作品",
    bounties: "Bounties",
    crafters: "Crafters",
    events: "カレンダー",
    hackathon: "ハッカソン",
    blog: "Journal",
    oss: "オープンソース",
    universe: "Crafter の世界",
    research: "リサーチ",
    impact: "インパクト",
    team: "チーム",
    ossMetrics: "OSS メトリクス",
    timeline: "プロジェクト活動",
    workWithUs: "協力する",
    brandPartnerships: "イベントと協力",
    contact: "お問い合わせ",
    communityCta: "コミュニティに参加",
    language: "言語",
    theme: "テーマ",
    openMenu: "メニューを開く",
  },
} as const
