export const navCopy = {
  en: {
    community: "Community",
    ships: "Ships",
    crafters: "Crafters",
    events: "Events",
    hackathon: "Hackathons",
    blog: "Blog",
    oss: "Open source",
    products: "Products",
    research: "Research",
    impact: "Impact",
    team: "Team",
    ossMetrics: "OSS metrics",
    timeline: "Project activity",
    workWithUs: "Work with us",
    brandPartnerships: "Brand partnerships",
    engineeringConsulting: "Engineering & design",
    contact: "Contact",
    communityCta: "Join the community",
    language: "Language",
    theme: "Theme",
    openMenu: "Open menu",
  },
  es: {
    community: "Comunidad",
    ships: "Ships",
    crafters: "Crafters",
    events: "Eventos",
    hackathon: "Hackathons",
    blog: "Blog",
    oss: "Código abierto",
    products: "Productos",
    research: "Investigación",
    impact: "Impacto",
    team: "Equipo",
    ossMetrics: "Métricas OSS",
    timeline: "Actividad de proyectos",
    workWithUs: "Trabaja con nosotros",
    brandPartnerships: "Partnerships de marca",
    engineeringConsulting: "Ingeniería y diseño",
    contact: "Contacto",
    communityCta: "Únete a la comunidad",
    language: "Idioma",
    theme: "Tema",
    openMenu: "Abrir menú",
  },
  pt: {
    community: "Comunidade",
    ships: "Ships",
    crafters: "Crafters",
    events: "Eventos",
    hackathon: "Hackathons",
    blog: "Blog",
    oss: "Codigo aberto",
    products: "Produtos",
    research: "Pesquisa",
    impact: "Impacto",
    team: "Equipe",
    ossMetrics: "Metricas OSS",
    timeline: "Atividade dos projetos",
    workWithUs: "Trabalhe conosco",
    brandPartnerships: "Parcerias de marca",
    engineeringConsulting: "Engenharia e design",
    contact: "Contato",
    communityCta: "Entre na comunidade",
    language: "Idioma",
    theme: "Tema",
    openMenu: "Abrir menu",
  },
  zh: {
    community: "社区",
    ships: "社区作品",
    crafters: "成员",
    events: "活动",
    hackathon: "黑客松",
    blog: "博客",
    oss: "开源",
    products: "产品",
    research: "研究",
    impact: "影响力",
    team: "团队",
    ossMetrics: "开源指标",
    timeline: "项目动态",
    workWithUs: "与我们合作",
    brandPartnerships: "品牌合作",
    engineeringConsulting: "工程与设计",
    contact: "联系我们",
    communityCta: "加入社区",
    language: "语言",
    theme: "主题",
    openMenu: "打开菜单",
  },
  ja: {
    community: "コミュニティ",
    ships: "コミュニティ作品",
    crafters: "Crafters",
    events: "イベント",
    hackathon: "ハッカソン",
    blog: "ブログ",
    oss: "オープンソース",
    products: "プロダクト",
    research: "リサーチ",
    impact: "インパクト",
    team: "チーム",
    ossMetrics: "OSS メトリクス",
    timeline: "プロジェクト活動",
    workWithUs: "一緒に働く",
    brandPartnerships: "ブランドパートナーシップ",
    engineeringConsulting: "エンジニアリング・デザイン",
    contact: "お問い合わせ",
    communityCta: "コミュニティに参加",
    language: "言語",
    theme: "テーマ",
    openMenu: "メニューを開く",
  },
} as const
