// The brand signature stays in English; interface copy follows the locale.
export const stationCopy = {
  en: {
    skip: "Skip to content", home: "Station", docs: "Documentation", more: "Explore Crafter",
    close: "Close menu", built: "Built in the open", join: "Come build with us",
    note: "Good things are made together.", family: "One family. Many ways to make.",
    hero: "Curious people. Things to make.", caption: "An idea is a beginning. Together is Crafter.",
    projects: "Made by Crafters.", projectsLabel: "Selected projects", explore: "Explore", visit: "Explore project",
    events: "See you out there.", eventsLabel: "Meet. Make. Repeat.",
    brew: "Good coffee, new ideas, and people who love to build.", ship: "A deadline, a crew, and something real to launch.",
    universe: "One family. Many ways to make.", universeBody: "A shared curiosity. Different places to take it.",
    station: "Community & open source", research: "Ideas & experiments", games: "Play & worlds", lab: "Tools & prototypes",
    search: "Search projects", searchPlaceholder: "Name, description, language…", empty: "No projects match these filters.", reset: "Clear filters",
    results: "projects", language: "Language", allLanguages: "All languages",
    guide: "The Station system.", guideIntro: "One visual language, across every surface. Change the theme to explore both palettes.",
    palette: "Color & contrast", typography: "Type with character", components: "Everyday components",
    primary: "Primary action", secondary: "Secondary action", field: "Your next project",
    disabled: "Disabled", light: "Light", dark: "Dark", system: "System", profile: "Edit profile", newShip: "Ship something", signIn: "Sign in",
  },
  es: {
    skip: "Saltar al contenido", home: "Station", docs: "Documentación", more: "Explorar Crafter",
    close: "Cerrar menú", built: "Hecho en abierto", join: "Vení a construir",
    note: "Las cosas buenas se hacen en compañía.", family: "Una familia. Muchas formas de hacer.",
    hero: "Gente curiosa. Cosas por hacer.", caption: "Una idea es un comienzo. Hacerla juntos es Crafter.",
    projects: "Hecho por Crafters.", projectsLabel: "Proyectos destacados", explore: "Explorar", visit: "Explorar proyecto",
    events: "Nos vemos afuera.", eventsLabel: "Encuentros que construyen",
    brew: "Buen café, nuevas ideas y gente con ganas de construir.", ship: "Una fecha, un equipo y algo real que lanzar.",
    universe: "Una familia. Muchas formas de hacer.", universeBody: "Una curiosidad compartida. Distintos lugares donde llevarla.",
    station: "Comunidad y código abierto", research: "Ideas y experimentos", games: "Juegos y mundos", lab: "Herramientas y prototipos",
    search: "Buscar proyectos", searchPlaceholder: "Nombre, descripción, lenguaje…", empty: "No hay proyectos con estos filtros.", reset: "Limpiar filtros",
    results: "proyectos", language: "Lenguaje", allLanguages: "Todos los lenguajes",
    guide: "El sistema Station.", guideIntro: "Un lenguaje visual para todo Crafter. Cambiá el tema para explorar ambas paletas.",
    palette: "Color y contraste", typography: "Tipografía con carácter", components: "Componentes de cada día",
    primary: "Acción principal", secondary: "Acción secundaria", field: "Tu próximo proyecto",
    disabled: "Deshabilitado", light: "Claro", dark: "Oscuro", system: "Sistema", profile: "Editar perfil", newShip: "Publicar un Ship", signIn: "Iniciar sesión",
  },
  pt: {
    skip: "Ir para o conteúdo", home: "Station", docs: "Documentação", more: "Explorar Crafter",
    close: "Fechar menu", built: "Feito em aberto", join: "Venha construir",
    note: "Coisas boas são feitas em companhia.", family: "Uma família. Muitas formas de criar.",
    hero: "Gente curiosa. Coisas para criar.", caption: "Uma ideia é o começo. Criar juntos é Crafter.",
    projects: "Feito por Crafters.", projectsLabel: "Projetos em destaque", explore: "Explorar", visit: "Explorar projeto",
    events: "Nos vemos por aí.", eventsLabel: "Encontros que constroem",
    brew: "Bom café, novas ideias e gente que gosta de construir.", ship: "Um prazo, uma equipe e algo real para lançar.",
    universe: "Uma família. Muitas formas de criar.", universeBody: "Uma curiosidade compartilhada. Diferentes caminhos para explorar.",
    station: "Comunidade e código aberto", research: "Ideias e experimentos", games: "Jogos e mundos", lab: "Ferramentas e protótipos",
    search: "Buscar projetos", searchPlaceholder: "Nome, descrição, linguagem…", empty: "Nenhum projeto corresponde a estes filtros.", reset: "Limpar filtros",
    results: "projetos", language: "Linguagem", allLanguages: "Todas as linguagens",
    guide: "O sistema Station.", guideIntro: "Uma linguagem visual em todo o Crafter. Mude o tema para explorar as duas paletas.",
    palette: "Cor e contraste", typography: "Tipografia com personalidade", components: "Componentes do dia a dia",
    primary: "Ação principal", secondary: "Ação secundária", field: "Seu próximo projeto",
    disabled: "Desativado", light: "Claro", dark: "Escuro", system: "Sistema", profile: "Editar perfil", newShip: "Publicar um Ship", signIn: "Entrar",
  },
  zh: {
    skip: "跳转到内容", home: "Station", docs: "文档", more: "探索 Crafter",
    close: "关闭菜单", built: "开放共建", join: "一起创造",
    note: "美好的事物，一起创造。", family: "一个大家庭，多种创造方式。",
    hero: "充满好奇，一起创造。", caption: "想法是起点。携手创造，就是 Crafter。",
    projects: "由 Crafters 打造。", projectsLabel: "精选项目", explore: "探索", visit: "探索项目",
    events: "线下见。", eventsLabel: "相聚、创造、再出发",
    brew: "好咖啡、新想法，还有热爱创造的人。", ship: "一个期限、一支团队，发布真正的作品。",
    universe: "一个大家庭。多种创造方式。", universeBody: "共同的好奇心，不同的探索方向。",
    station: "社区与开源", research: "想法与实验", games: "游戏与世界", lab: "工具与原型",
    search: "搜索项目", searchPlaceholder: "名称、描述、编程语言…", empty: "没有符合筛选条件的项目。", reset: "清除筛选",
    results: "个项目", language: "编程语言", allLanguages: "所有语言",
    guide: "Station 设计系统。", guideIntro: "贯穿 Crafter 的视觉语言。切换主题，探索两种配色。",
    palette: "颜色与对比", typography: "有个性的字体", components: "日常组件",
    primary: "主要操作", secondary: "次要操作", field: "你的下一个项目",
    disabled: "已禁用", light: "浅色", dark: "深色", system: "跟随系统", profile: "编辑资料", newShip: "发布作品", signIn: "登录",
  },
  ja: {
    skip: "コンテンツへ", home: "Station", docs: "ドキュメント", more: "Crafter を探索",
    close: "メニューを閉じる", built: "オープンにつくる", join: "一緒につくろう",
    note: "いいものは、一緒につくる。", family: "ひとつの家族。つくり方は、いろいろ。",
    hero: "好奇心のある人。つくりたいもの。", caption: "アイデアは始まり。一緒につくるのが Crafter。",
    projects: "Crafters がつくる。", projectsLabel: "注目のプロジェクト", explore: "詳しく見る", visit: "プロジェクトを見る",
    events: "会いに行こう。", eventsLabel: "出会い、つくり、また集まる",
    brew: "おいしいコーヒー、新しいアイデア、つくることが好きな仲間。", ship: "締め切りと仲間。そして、本当にリリースできるもの。",
    universe: "ひとつの家族。つくり方は、いろいろ。", universeBody: "共通する好奇心。広がる探究のかたち。",
    station: "コミュニティとオープンソース", research: "アイデアと実験", games: "ゲームと世界", lab: "ツールとプロトタイプ",
    search: "プロジェクトを検索", searchPlaceholder: "名前、説明、プログラミング言語…", empty: "条件に一致するプロジェクトはありません。", reset: "絞り込みをクリア",
    results: "プロジェクト", language: "言語", allLanguages: "すべての言語",
    guide: "Station デザインシステム。", guideIntro: "Crafter 全体をつなぐ視覚言語。テーマを切り替えて両方のパレットをご覧ください。",
    palette: "色とコントラスト", typography: "個性のある文字", components: "日常のコンポーネント",
    primary: "メインの操作", secondary: "補助の操作", field: "次のプロジェクト",
    disabled: "無効", light: "ライト", dark: "ダーク", system: "システム", profile: "プロフィール編集", newShip: "作品を公開", signIn: "ログイン",
  },
} as const
