export const ISO_COUNTRIES = [
  ["AD", "Andorra"],
  ["AE", "United Arab Emirates"],
  ["AF", "Afghanistan"],
  ["AG", "Antigua and Barbuda"],
  ["AI", "Anguilla"],
  ["AL", "Albania"],
  ["AM", "Armenia"],
  ["AO", "Angola"],
  ["AQ", "Antarctica"],
  ["AR", "Argentina"],
  ["AS", "American Samoa"],
  ["AT", "Austria"],
  ["AU", "Australia"],
  ["AW", "Aruba"],
  ["AX", "Åland Islands"],
  ["AZ", "Azerbaijan"],
  ["BA", "Bosnia and Herzegovina"],
  ["BB", "Barbados"],
  ["BD", "Bangladesh"],
  ["BE", "Belgium"],
  ["BF", "Burkina Faso"],
  ["BG", "Bulgaria"],
  ["BH", "Bahrain"],
  ["BI", "Burundi"],
  ["BJ", "Benin"],
  ["BL", "Saint Barthélemy"],
  ["BM", "Bermuda"],
  ["BN", "Brunei"],
  ["BO", "Bolivia"],
  ["BQ", "Caribbean Netherlands"],
  ["BR", "Brazil"],
  ["BS", "Bahamas"],
  ["BT", "Bhutan"],
  ["BV", "Bouvet Island"],
  ["BW", "Botswana"],
  ["BY", "Belarus"],
  ["BZ", "Belize"],
  ["CA", "Canada"],
  ["CC", "Cocos Islands"],
  ["CD", "Congo (DRC)"],
  ["CF", "Central African Republic"],
  ["CG", "Congo"],
  ["CH", "Switzerland"],
  ["CI", "Côte d'Ivoire"],
  ["CK", "Cook Islands"],
  ["CL", "Chile"],
  ["CM", "Cameroon"],
  ["CN", "China"],
  ["CO", "Colombia"],
  ["CR", "Costa Rica"],
  ["CU", "Cuba"],
  ["CV", "Cabo Verde"],
  ["CW", "Curaçao"],
  ["CX", "Christmas Island"],
  ["CY", "Cyprus"],
  ["CZ", "Czechia"],
  ["DE", "Germany"],
  ["DJ", "Djibouti"],
  ["DK", "Denmark"],
  ["DM", "Dominica"],
  ["DO", "Dominican Republic"],
  ["DZ", "Algeria"],
  ["EC", "Ecuador"],
  ["EE", "Estonia"],
  ["EG", "Egypt"],
  ["EH", "Western Sahara"],
  ["ER", "Eritrea"],
  ["ES", "Spain"],
  ["ET", "Ethiopia"],
  ["FI", "Finland"],
  ["FJ", "Fiji"],
  ["FK", "Falkland Islands"],
  ["FM", "Micronesia"],
  ["FO", "Faroe Islands"],
  ["FR", "France"],
  ["GA", "Gabon"],
  ["GB", "United Kingdom"],
  ["GD", "Grenada"],
  ["GE", "Georgia"],
  ["GF", "French Guiana"],
  ["GG", "Guernsey"],
  ["GH", "Ghana"],
  ["GI", "Gibraltar"],
  ["GL", "Greenland"],
  ["GM", "Gambia"],
  ["GN", "Guinea"],
  ["GP", "Guadeloupe"],
  ["GQ", "Equatorial Guinea"],
  ["GR", "Greece"],
  ["GS", "South Georgia"],
  ["GT", "Guatemala"],
  ["GU", "Guam"],
  ["GW", "Guinea-Bissau"],
  ["GY", "Guyana"],
  ["HK", "Hong Kong"],
  ["HM", "Heard Island"],
  ["HN", "Honduras"],
  ["HR", "Croatia"],
  ["HT", "Haiti"],
  ["HU", "Hungary"],
  ["ID", "Indonesia"],
  ["IE", "Ireland"],
  ["IL", "Israel"],
  ["IM", "Isle of Man"],
  ["IN", "India"],
  ["IO", "British Indian Ocean Territory"],
  ["IQ", "Iraq"],
  ["IR", "Iran"],
  ["IS", "Iceland"],
  ["IT", "Italy"],
  ["JE", "Jersey"],
  ["JM", "Jamaica"],
  ["JO", "Jordan"],
  ["JP", "Japan"],
  ["KE", "Kenya"],
  ["KG", "Kyrgyzstan"],
  ["KH", "Cambodia"],
  ["KI", "Kiribati"],
  ["KM", "Comoros"],
  ["KN", "Saint Kitts and Nevis"],
  ["KP", "North Korea"],
  ["KR", "South Korea"],
  ["KW", "Kuwait"],
  ["KY", "Cayman Islands"],
  ["KZ", "Kazakhstan"],
  ["LA", "Laos"],
  ["LB", "Lebanon"],
  ["LC", "Saint Lucia"],
  ["LI", "Liechtenstein"],
  ["LK", "Sri Lanka"],
  ["LR", "Liberia"],
  ["LS", "Lesotho"],
  ["LT", "Lithuania"],
  ["LU", "Luxembourg"],
  ["LV", "Latvia"],
  ["LY", "Libya"],
  ["MA", "Morocco"],
  ["MC", "Monaco"],
  ["MD", "Moldova"],
  ["ME", "Montenegro"],
  ["MF", "Saint Martin"],
  ["MG", "Madagascar"],
  ["MH", "Marshall Islands"],
  ["MK", "North Macedonia"],
  ["ML", "Mali"],
  ["MM", "Myanmar"],
  ["MN", "Mongolia"],
  ["MO", "Macao"],
  ["MP", "Northern Mariana Islands"],
  ["MQ", "Martinique"],
  ["MR", "Mauritania"],
  ["MS", "Montserrat"],
  ["MT", "Malta"],
  ["MU", "Mauritius"],
  ["MV", "Maldives"],
  ["MW", "Malawi"],
  ["MX", "Mexico"],
  ["MY", "Malaysia"],
  ["MZ", "Mozambique"],
  ["NA", "Namibia"],
  ["NC", "New Caledonia"],
  ["NE", "Niger"],
  ["NF", "Norfolk Island"],
  ["NG", "Nigeria"],
  ["NI", "Nicaragua"],
  ["NL", "Netherlands"],
  ["NO", "Norway"],
  ["NP", "Nepal"],
  ["NR", "Nauru"],
  ["NU", "Niue"],
  ["NZ", "New Zealand"],
  ["OM", "Oman"],
  ["PA", "Panama"],
  ["PE", "Peru"],
  ["PF", "French Polynesia"],
  ["PG", "Papua New Guinea"],
  ["PH", "Philippines"],
  ["PK", "Pakistan"],
  ["PL", "Poland"],
  ["PM", "Saint Pierre and Miquelon"],
  ["PN", "Pitcairn"],
  ["PR", "Puerto Rico"],
  ["PS", "Palestine"],
  ["PT", "Portugal"],
  ["PW", "Palau"],
  ["PY", "Paraguay"],
  ["QA", "Qatar"],
  ["RE", "Réunion"],
  ["RO", "Romania"],
  ["RS", "Serbia"],
  ["RU", "Russia"],
  ["RW", "Rwanda"],
  ["SA", "Saudi Arabia"],
  ["SB", "Solomon Islands"],
  ["SC", "Seychelles"],
  ["SD", "Sudan"],
  ["SE", "Sweden"],
  ["SG", "Singapore"],
  ["SH", "Saint Helena"],
  ["SI", "Slovenia"],
  ["SJ", "Svalbard and Jan Mayen"],
  ["SK", "Slovakia"],
  ["SL", "Sierra Leone"],
  ["SM", "San Marino"],
  ["SN", "Senegal"],
  ["SO", "Somalia"],
  ["SR", "Suriname"],
  ["SS", "South Sudan"],
  ["ST", "Sao Tome and Principe"],
  ["SV", "El Salvador"],
  ["SX", "Sint Maarten"],
  ["SY", "Syria"],
  ["SZ", "Eswatini"],
  ["TC", "Turks and Caicos Islands"],
  ["TD", "Chad"],
  ["TF", "French Southern Territories"],
  ["TG", "Togo"],
  ["TH", "Thailand"],
  ["TJ", "Tajikistan"],
  ["TK", "Tokelau"],
  ["TL", "Timor-Leste"],
  ["TM", "Turkmenistan"],
  ["TN", "Tunisia"],
  ["TO", "Tonga"],
  ["TR", "Turkey"],
  ["TT", "Trinidad and Tobago"],
  ["TV", "Tuvalu"],
  ["TW", "Taiwan"],
  ["TZ", "Tanzania"],
  ["UA", "Ukraine"],
  ["UG", "Uganda"],
  ["UM", "U.S. Outlying Islands"],
  ["US", "United States"],
  ["UY", "Uruguay"],
  ["UZ", "Uzbekistan"],
  ["VA", "Vatican City"],
  ["VC", "Saint Vincent and the Grenadines"],
  ["VE", "Venezuela"],
  ["VG", "British Virgin Islands"],
  ["VI", "U.S. Virgin Islands"],
  ["VN", "Vietnam"],
  ["VU", "Vanuatu"],
  ["WF", "Wallis and Futuna"],
  ["WS", "Samoa"],
  ["YE", "Yemen"],
  ["YT", "Mayotte"],
  ["ZA", "South Africa"],
  ["ZM", "Zambia"],
  ["ZW", "Zimbabwe"],
] as const

export type IsoCountryCode = (typeof ISO_COUNTRIES)[number][0]

export type ProfileCity = {
  city: string
  countryCode: IsoCountryCode
  region: string | null
}

export const PROFILE_CITIES: ProfileCity[] = [
  { city: "Buenos Aires", countryCode: "AR", region: "Buenos Aires" },
  { city: "Córdoba", countryCode: "AR", region: "Córdoba" },
  { city: "Rosario", countryCode: "AR", region: "Santa Fe" },
  { city: "Mendoza", countryCode: "AR", region: "Mendoza" },
  { city: "La Plata", countryCode: "AR", region: "Buenos Aires" },
  { city: "San Miguel de Tucumán", countryCode: "AR", region: "Tucumán" },
  { city: "Bariloche", countryCode: "AR", region: "Río Negro" },
  { city: "Mar del Plata", countryCode: "AR", region: "Buenos Aires" },
  { city: "Salta", countryCode: "AR", region: "Salta" },
  { city: "La Paz", countryCode: "BO", region: "La Paz" },
  { city: "Santa Cruz de la Sierra", countryCode: "BO", region: "Santa Cruz" },
  { city: "Cochabamba", countryCode: "BO", region: "Cochabamba" },
  { city: "São Paulo", countryCode: "BR", region: "São Paulo" },
  { city: "Rio de Janeiro", countryCode: "BR", region: "Rio de Janeiro" },
  { city: "Belo Horizonte", countryCode: "BR", region: "Minas Gerais" },
  { city: "Brasília", countryCode: "BR", region: "Federal District" },
  { city: "Curitiba", countryCode: "BR", region: "Paraná" },
  { city: "Porto Alegre", countryCode: "BR", region: "Rio Grande do Sul" },
  { city: "Recife", countryCode: "BR", region: "Pernambuco" },
  { city: "Salvador", countryCode: "BR", region: "Bahia" },
  { city: "Fortaleza", countryCode: "BR", region: "Ceará" },
  { city: "Florianópolis", countryCode: "BR", region: "Santa Catarina" },
  { city: "Campinas", countryCode: "BR", region: "São Paulo" },
  { city: "Santiago", countryCode: "CL", region: "Santiago Metropolitan" },
  { city: "Valparaíso", countryCode: "CL", region: "Valparaíso" },
  { city: "Concepción", countryCode: "CL", region: "Biobío" },
  { city: "Valdivia", countryCode: "CL", region: "Los Ríos" },
  { city: "Antofagasta", countryCode: "CL", region: "Antofagasta" },
  { city: "Bogotá", countryCode: "CO", region: "Bogotá" },
  { city: "Medellín", countryCode: "CO", region: "Antioquia" },
  { city: "Cali", countryCode: "CO", region: "Valle del Cauca" },
  { city: "Barranquilla", countryCode: "CO", region: "Atlántico" },
  { city: "Cartagena", countryCode: "CO", region: "Bolívar" },
  { city: "Bucaramanga", countryCode: "CO", region: "Santander" },
  { city: "San José", countryCode: "CR", region: "San José" },
  { city: "Havana", countryCode: "CU", region: "Havana" },
  { city: "Santo Domingo", countryCode: "DO", region: "Nacional" },
  { city: "Santiago de los Caballeros", countryCode: "DO", region: "Santiago" },
  { city: "Quito", countryCode: "EC", region: "Pichincha" },
  { city: "Guayaquil", countryCode: "EC", region: "Guayas" },
  { city: "Cuenca", countryCode: "EC", region: "Azuay" },
  { city: "San Salvador", countryCode: "SV", region: "San Salvador" },
  { city: "Guatemala City", countryCode: "GT", region: "Guatemala" },
  { city: "Tegucigalpa", countryCode: "HN", region: "Francisco Morazán" },
  { city: "San Pedro Sula", countryCode: "HN", region: "Cortés" },
  { city: "Mexico City", countryCode: "MX", region: "Mexico City" },
  { city: "Guadalajara", countryCode: "MX", region: "Jalisco" },
  { city: "Monterrey", countryCode: "MX", region: "Nuevo León" },
  { city: "Puebla", countryCode: "MX", region: "Puebla" },
  { city: "Tijuana", countryCode: "MX", region: "Baja California" },
  { city: "Mérida", countryCode: "MX", region: "Yucatán" },
  { city: "Querétaro", countryCode: "MX", region: "Querétaro" },
  { city: "León", countryCode: "MX", region: "Guanajuato" },
  { city: "Cancún", countryCode: "MX", region: "Quintana Roo" },
  { city: "Managua", countryCode: "NI", region: "Managua" },
  { city: "Panama City", countryCode: "PA", region: "Panamá" },
  { city: "Asunción", countryCode: "PY", region: "Asunción" },
  { city: "Lima", countryCode: "PE", region: "Lima" },
  { city: "Arequipa", countryCode: "PE", region: "Arequipa" },
  { city: "Cusco", countryCode: "PE", region: "Cusco" },
  { city: "Trujillo", countryCode: "PE", region: "La Libertad" },
  { city: "Piura", countryCode: "PE", region: "Piura" },
  { city: "Chiclayo", countryCode: "PE", region: "Lambayeque" },
  { city: "San Juan", countryCode: "PR", region: "San Juan" },
  { city: "Montevideo", countryCode: "UY", region: "Montevideo" },
  { city: "Punta del Este", countryCode: "UY", region: "Maldonado" },
  { city: "Caracas", countryCode: "VE", region: "Capital District" },
  { city: "Maracaibo", countryCode: "VE", region: "Zulia" },
  { city: "Valencia", countryCode: "VE", region: "Carabobo" },
  { city: "Kingston", countryCode: "JM", region: "Kingston" },
  { city: "Toronto", countryCode: "CA", region: "Ontario" },
  { city: "Vancouver", countryCode: "CA", region: "British Columbia" },
  { city: "Montreal", countryCode: "CA", region: "Quebec" },
  { city: "Ottawa", countryCode: "CA", region: "Ontario" },
  { city: "Calgary", countryCode: "CA", region: "Alberta" },
  { city: "New York", countryCode: "US", region: "New York" },
  { city: "San Francisco", countryCode: "US", region: "California" },
  { city: "Los Angeles", countryCode: "US", region: "California" },
  { city: "Seattle", countryCode: "US", region: "Washington" },
  { city: "Austin", countryCode: "US", region: "Texas" },
  { city: "Chicago", countryCode: "US", region: "Illinois" },
  { city: "Boston", countryCode: "US", region: "Massachusetts" },
  { city: "Miami", countryCode: "US", region: "Florida" },
  { city: "Denver", countryCode: "US", region: "Colorado" },
  { city: "Atlanta", countryCode: "US", region: "Georgia" },
  { city: "Portland", countryCode: "US", region: "Oregon" },
  { city: "Washington", countryCode: "US", region: "District of Columbia" },
  { city: "San Diego", countryCode: "US", region: "California" },
  { city: "Philadelphia", countryCode: "US", region: "Pennsylvania" },
  { city: "Dallas", countryCode: "US", region: "Texas" },
  { city: "Houston", countryCode: "US", region: "Texas" },
  { city: "Raleigh", countryCode: "US", region: "North Carolina" },
  { city: "Boulder", countryCode: "US", region: "Colorado" },
  { city: "Nashville", countryCode: "US", region: "Tennessee" },
  { city: "Madrid", countryCode: "ES", region: "Madrid" },
  { city: "Barcelona", countryCode: "ES", region: "Catalonia" },
  { city: "Valencia", countryCode: "ES", region: "Valencia" },
  { city: "Seville", countryCode: "ES", region: "Andalusia" },
  { city: "Córdoba", countryCode: "ES", region: "Andalusia" },
  { city: "Málaga", countryCode: "ES", region: "Andalusia" },
  { city: "Bilbao", countryCode: "ES", region: "Basque Country" },
  { city: "Lisbon", countryCode: "PT", region: "Lisbon" },
  { city: "Porto", countryCode: "PT", region: "Porto" },
  { city: "London", countryCode: "GB", region: "England" },
  { city: "Manchester", countryCode: "GB", region: "England" },
  { city: "Edinburgh", countryCode: "GB", region: "Scotland" },
  { city: "Paris", countryCode: "FR", region: "Île-de-France" },
  { city: "Lyon", countryCode: "FR", region: "Auvergne-Rhône-Alpes" },
  { city: "Berlin", countryCode: "DE", region: "Berlin" },
  { city: "Munich", countryCode: "DE", region: "Bavaria" },
  { city: "Hamburg", countryCode: "DE", region: "Hamburg" },
  { city: "Amsterdam", countryCode: "NL", region: "North Holland" },
  { city: "Rotterdam", countryCode: "NL", region: "South Holland" },
  { city: "Dublin", countryCode: "IE", region: "Leinster" },
  { city: "Rome", countryCode: "IT", region: "Lazio" },
  { city: "Milan", countryCode: "IT", region: "Lombardy" },
  { city: "Zurich", countryCode: "CH", region: "Zurich" },
  { city: "Geneva", countryCode: "CH", region: "Geneva" },
  { city: "Stockholm", countryCode: "SE", region: "Stockholm" },
  { city: "Copenhagen", countryCode: "DK", region: "Capital Region" },
  { city: "Oslo", countryCode: "NO", region: "Oslo" },
  { city: "Helsinki", countryCode: "FI", region: "Uusimaa" },
  { city: "Vienna", countryCode: "AT", region: "Vienna" },
  { city: "Prague", countryCode: "CZ", region: "Prague" },
  { city: "Warsaw", countryCode: "PL", region: "Mazovia" },
  { city: "Brussels", countryCode: "BE", region: "Brussels" },
  { city: "Tokyo", countryCode: "JP", region: "Tokyo" },
  { city: "Osaka", countryCode: "JP", region: "Osaka" },
  { city: "Seoul", countryCode: "KR", region: "Seoul" },
  { city: "Singapore", countryCode: "SG", region: null },
  { city: "Hong Kong", countryCode: "HK", region: null },
  { city: "Taipei", countryCode: "TW", region: "Taipei" },
  { city: "Bangkok", countryCode: "TH", region: "Bangkok" },
  { city: "Jakarta", countryCode: "ID", region: "Jakarta" },
  { city: "Manila", countryCode: "PH", region: "Metro Manila" },
  { city: "Kuala Lumpur", countryCode: "MY", region: "Kuala Lumpur" },
  { city: "Ho Chi Minh City", countryCode: "VN", region: "Ho Chi Minh City" },
  { city: "Hanoi", countryCode: "VN", region: "Hanoi" },
  { city: "Bengaluru", countryCode: "IN", region: "Karnataka" },
  { city: "Mumbai", countryCode: "IN", region: "Maharashtra" },
  { city: "Delhi", countryCode: "IN", region: "Delhi" },
  { city: "Hyderabad", countryCode: "IN", region: "Telangana" },
  { city: "Pune", countryCode: "IN", region: "Maharashtra" },
  { city: "Sydney", countryCode: "AU", region: "New South Wales" },
  { city: "Melbourne", countryCode: "AU", region: "Victoria" },
  { city: "Auckland", countryCode: "NZ", region: "Auckland" },
  { city: "Cape Town", countryCode: "ZA", region: "Western Cape" },
  { city: "Johannesburg", countryCode: "ZA", region: "Gauteng" },
  { city: "Lagos", countryCode: "NG", region: "Lagos" },
  { city: "Nairobi", countryCode: "KE", region: "Nairobi" },
  { city: "Cairo", countryCode: "EG", region: "Cairo" },
  { city: "Tel Aviv", countryCode: "IL", region: "Tel Aviv" },
  { city: "Dubai", countryCode: "AE", region: "Dubai" },
  { city: "Abu Dhabi", countryCode: "AE", region: "Abu Dhabi" },
  { city: "Casablanca", countryCode: "MA", region: "Casablanca-Settat" },
]
