import { handle } from "hono/vercel"

// Generated by the package build before Vercel bundles this function.
// @ts-expect-error The generated JavaScript bundle has no declaration file.
import app from "../dist/index.js"

export default handle(app)
